### ISSUE TITLE
OAI: LAC Theses Canada identifier

### ISSUE THREAD

**Issue by anayram** [ualbertalib/HydraNorth#1004]
In ETD-MS responses LAC requires a second identifier element (also in the descriptive metadata section) that should contain the university's library symbol in the format:
`<identifier>TC-[Library Symbol]-[Unique Number]</identifier>`

This is not required in the Dublin Core metadata.

From: http://www.bac-lac.gc.ca/eng/services/theses/Pages/harvesting.aspx
> A valid TC [Theses Canada] number is provided and contains your library symbol (AEU) and a unique internal number not exceeding 15 characters.

**Comment by anayram** [comment]
University of Alberta Libraries symbol is AEU.

LAC checks for duplicates by theses' TC number. The highest number harvested for UAL was TC-AEU-33238.

We need to either keep the TC numbering the same or to contact LAC about any changes to those IDs (maybe provide old TC - new TC mappings?).

**Comment by piyapongch** [comment]
What is [Unique Number] to use? Is it NOID?

**Comment by pbinkley** [comment]
The unique number in the TC number is based on the handle. For old DSpace
item is just the number of the handle; for items deposited after the
migration from DSpace to Fedora, when we had to get a new handle prefix, we
used the handle number + 2000 to avoid conflicting with the first series.
This was done in the XSL stylesheet that generated the ETDMS records, which
is embedded in the thesisdeposit code in lib, I think.

Peter

Peter Binkley, Ph.D., MLIS
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

On 14 March 2016 at 14:35, Piyapong Charoenwattana <notifications@github.com

**Comment by piyapongch** [comment]
I can generate the unique number from the handle field. What should be use for no handle item?

**Comment by pbinkley** [comment]
LAC seems to require a number and not just a unique string, so we should
continue the numbering from the last handle.

Peter

Peter Binkley, Ph.D., MLIS
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

On 16 March 2016 at 11:00, Piyapong Charoenwattana <notifications@github.com

**Comment by anayram** [comment]
Maybe this is a question for @pbinkley and @sfarnel 

I don't know whether keeping old TC numbers based on handles and new TC numbers based on a different id is a good idea.

Should we re-start the numbering all over again or keep the old ones?

**Comment by pbinkley** [comment]
And I guess that means we need to start storing the TC field as an proper metadata field in it's own property, and generate the TC number when an item is created. I wish I'd thought of that before migration. I think we can add this functionality to the ARK creation process, since it already kicks in when a new item is created.

**Comment by pbinkley** [comment]
Second thought: TC numbers are only required for theses, and theses only come into ERA from thesisdeposit, which is still creating handles for new theses. Therefore there will be no items that need TC numbers that don't have handles until thesisdeposit is shut down, which won't be for another year at least. I think we should leave this problem alone until then, in the interest of getting the OAI server deployed soon.

@piyapongch @sfarnel @anayram @sfbetz @leahvanderjagt @weiweishi does this make sense?

**Comment by anayram** [comment]
This sounds good, and this way we won't need to provide TC number mappings to LAC since we will keep old ids.

**Comment by anayram** [comment]
To store TC numbers, should we use a local property? E.g. ualid:tc
@sfarnel @pbinkley @weiweishi 

In any case we should make sure we keep this in line with the local namespace uris and prefixes as well as to register it in the data dictionary.

**Comment by sfbetz** [comment]
Makes sense to me. 

However, there is the case of St Stephen's College. We do not yet have their theses but should think about how to handle them once they have them ready to go, and how we might be able to enable LAC harvesting of that collection. They will likely be ingested via batch ingest process... They of course will have a different prefix (not AEU). Volume will be low... a few hundred items.

**Comment by piyapongch** [comment]
I will use the handle to generate the LAC Identifier.

**Comment by sfarnel** [comment]
Yes, need to account for these and others that may come in. We could look
to collection differentiation to help with this.

Sent from my iPhone

On Mar 16, 2016, at 12:57 PM, Sonya Betz <notifications@github.com> wrote:

Makes sense to me.

However, there is the case of St Stephen's College. We do not yet have
their theses but should think about how to handle them once they have them
ready to go, and how we might be able to enable LAC harvesting of that
collection. They will likely be ingested via batch ingest process... They
of course will have a different prefix (not AEU). Volume will be low... a
few hundred items.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/ualbertalib/HydraNorth/issues/1004#issuecomment-197489749>

**Comment by piyapongch** [comment]
I have added the LAC Identifier to OAI provider module. Here is a sample, <etd_ms:identifier>TC-AEU-10402/era.28237</etd_ms:identifier>.

**Comment by pbinkley** [comment]
It needs to have just handle number: TC-AEU-28237

Peter

Peter Binkley, Ph.D., MLIS
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

On 18 March 2016 at 11:30, Piyapong Charoenwattana <notifications@github.com

**Comment by weiweishi** [comment]
We(Metadata team and me) had a discussion last week about this, and agreed
that we should keep this identifier as a property on the object in Fedora,
so that we can avoid constructing it from handle every single time we
deploy a new OAI provider. It can be part of big update write job to
Fedora. What do you think @pbinkley?

Weiwei

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by piyapongch** [comment]
I will change to this format, TC-AEU-28237 for now.

Let me know when you have Fedora property ready. I will need to know the
property name to create the OAI response element.


Piyapong.

**Comment by anayram** [comment]
This property has been assigned as `ualid:thesescanada`

**Comment by piyapongch** [comment]
Can you give me the URI for ualid? Is it in the data dictionary?

I will map it to the response element.


Piyapong.

**Comment by piyapongch** [comment]
I have added all UALib namespaces from the data dictionary to Fedora 4 JCR configuration.

**Comment by pbinkley** [comment]
In answer to Weiwei's comment: I wouldn't want the use of a new property to hold up the OAI deployment, if the OAI is ready to go using calculation based on handles, within the context I outlined in my "second thought" comment above. If we need to handle the case of objects without handles that need TC numbers in the future, (or if I missed something in that comment,) we can build out the necessary changes then. I think this is good YAGNI process.

**Comment by sfarnel** [comment]
Knowing we'll have at least some other theses that will need a different
code, does it make it simpler to generate all of them and store as
properties in the items, or generate on the fly using a more complex set of
rules? Perhaps a case of six of one, half dozen of the other?

Sent from my iPhone

On Mar 21, 2016, at 5:18 PM, Peter Binkley <notifications@github.com> wrote:

In answer to Weiwei's comment: I wouldn't want the use of a new property to
hold up the OAI deployment, if the OAI is ready to go using calculation
based on handles, within the context I outlined in my "second thought"
comment above. If we need to handle the case of objects without handles
that need TC numbers in the future, (or if I missed something in that
comment,) we can build out the necessary changes then. I think this is good
YAGNI process.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/ualbertalib/HydraNorth/issues/1004#issuecomment-199531387>

**Comment by pbinkley** [comment]
What I want to avoid is making the pending OAI deployment depend on the big batch job that would be needed to populate the TC property for all the existing theses.

**Comment by anayram** [comment]
@piyapongch should this identifier be available now on plano or era-test or is it waiting to be deployed?

**Comment by piyapongch** [comment]
It is on both plano and era-test.

Piyapong.

**Comment by anayram** [comment]
Thanks, just checked and it is all good. Can this ticket be closed or should we keep it open until a decision has been made about pulling the TC number from the data vs. generating it on the fly from handles?

**Comment by piyapongch** [comment]
Right now, it is generated from the fedora3handle property. I think you can
leave it for now. We will discuss about it and make a final decision.


Piyapong.

**Comment by anayram** [comment]
We will just generate it from handles for now. When handles are no longer supported (i.e. no longer coming from thesisdeposit) team will come back to this question.

**Comment by anayram** [comment]
TC number generation needs to be updated to add +2000 count to number in cases where handle contains `era.`

**Comment by anayram** [comment]
All good. Closing issue.
