### ISSUE TITLE
Create a good four-digit date field

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#1042]
Replace the current year_created field with a well-though-out four-digit date field for use in faceting in the public interface and for reporting publication year in DOI and ARK. It should work well with all of our content types and sources (Dataverse etc.)

**Comment by pbinkley** [comment]
Note: we're still allowing null value in date field for ARK metadata.

**Comment by johnhuck** [comment]
When I made the ARK metadata recommendations, I identified different kinds of observed values in the ERA date created field (I think it was) that a regex would probably not easily resolve to a 4 digit year for ARK registration and suggested that those cases would need further study, since publication year is a required element for ARK registration. This sounds like it might be related (?) Let me know if I can be of assistance.

**Comment by pbinkley** [comment]
This issue was moved to ualbertalib/Hydranorth2#105
