### ISSUE TITLE
date_modified used the wrong datetime value/zone when record is modified

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#1061]
@pbinkley has noticed that when a record is updated, the date_modified date is set incorrect, with current MST but set in UTC timezone. 

eg: an object updated on 11:01 MST shows date_modified as: Wed, 20 Apr 2016 11:01:30 +0000

Further investigation discovered that this is a bug in older version of Sufia:
https://github.com/projecthydra/sufia/blob/v6.2.0/app/controllers/concerns/sufia/batch_edits_controller_behavior.rb#L51

It uses Time.now instead of Time.current or Time.zone.now to get the time. 

This will affect OAI harvesting.

**Comment by mbarnett** [comment]
Ugh, Date/Time code is such a mess. I got curious, and when you fix this you might want to sanity check this, as well:

ActiveFedora's Solr indexer will dump a DateTime object with MDT or MST offset (depending on the time of year) into Solr if dateModified is blank https://github.com/projecthydra/active_fedora/blob/e1391fb0dd4108923b02a3dfb344a19dd971a6f8/lib/active_fedora/indexing_service.rb#L66.

Depending on how the actual serialization in Solr takes place, the dates *may* all get normalized, but since we rely heavily on Solr for caching it might be worth checking to see whether or not there are any weird bugs that crop up from inconsistencies between raw UTC in that field, or Timezoned values.

**Comment by anayram** [comment]
Great, yes, dcterms:modified should then be mapped for OAI datestamp, I'll add this info to the relevant ticket #820
