### ISSUE TITLE
Cronjob to generate sitemap in production

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#1070]
We need to run this command as a cronjob nightly: ```bundle exec rake sitemap:generate```. This causes the sitemap.xml (and potentially more files since the sitemap is paginated) in ```public/```, and it will be downloadable at ```https://era.library.ualberta.ca/sitemap.xml```. This job can be run on one app server and then the ```public/``` directory can be replicated to the other.

**Comment by weiweishi** [comment]
The task is completed in 5 minutes on each era-test app server. So the cronjob can probably be scheduled to run anytime overnight as it won't take much time.

The generated sitemaps will be available at:
https://era.library.ualberta.ca/sitemap.xml, and 4 fragment files.

The successful completion of the rake task will generate new sitemap files at public/sitemap.xml and public/sitemaps. So monitoring the timestamps and sizes of these files could be an indication of a successful run of the cronjob.

The command to use is:
RAILS_ENV={{ RAILS_ENV }} bundle exec rake sitemap:generate

**Comment by henryzhang87** [comment]
The reason for running the rake task on one server not two servers or more is because there is a xml field for "last modified" timestamp. This can avoid timestamp discrepancy.

We would like to have high availability for the sitemap.xml resources to the end user. So, replicate from one application server to the other is desirable.

The downside is we will have a messy ansible playbook. The playbook needs to
1. generate public/private SSL keys on servers that replicate sitemap
2. place the public key to the server that runs the rake task
3. the server running rake task needs to have a cron job to schedule the rake task
4. the servers not running rake task need to have a cron job to replicate
