### ISSUE TITLE
Resource Type attribute of Collection

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/HydraNorth#108]
Sufia allows this to be a choice while ERA draws from the type of the items. Discussion unresolved, may require more discussion.

**Comment by pbinkley** [comment]
Question for @sfbetz : anything you want us to do?
Also: how might this be used in digitization phase?

**Comment by sfbetz** [comment]
So, if I understand this, this is a way to set resource type for a collection? Would these be distinct from the resource type for items - meaning a separate set of resource type that could be applied to collections? 

I'm not sure of the utility for our current repository - but could see applications for how different collections might be displayed (eg display photo collections in nice tiled galleries, display articles in a list with certain metadata, etc).

**Comment by sfarnel** [comment]
I think in some cases this would make sense since some collections do
indeed have a single item type in them. Others, though, have a range of
item types and so that would have to be accounted for. The other thing
would be how this would behave; is it simple a piece of descriptive
information , or would it be meant to do more, i.e., to assert control over
the collection? So, for example, if a collection had item type image but
someone uploaded an article, would it simply update to have item types
image and article? Or would it be the case that if a collection were of
type image, no item of a type other than image could be uploaded to it?
This would have impact on the deposit form and the order of the deposit
process.

Each item has a type which allows users to browse/facet/search. Would there
be use in labeling at the collection level? Would users want to be able to
limit to collections that were images only, say? I could see that. But if
most collections are mixed, would we include only pure image collections?
Or any that had images, or only a certain percentage of them?

Would be interesting to think through some potential use cases.

On Wed, Feb 3, 2016 at 3:32 PM, Sonya Betz <notifications@github.com> wrote:

> So, if I understand this, this is a way to set resource type for a
> collection? Would these be distinct from the resource type for items -
> meaning a separate set of resource type that could be applied to
> collections?
>
> I'm not sure of the utility for our current repository - but could see
> applications for how different collections might be displayed (eg display
> photo collections in nice tiled galleries, display articles in a list with
> certain metadata, etc).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/108#issuecomment-179505736>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by pgwillia** [comment]
@sfbetz mentioned this as a shortcoming at today's meeting. Would be especially useful for Admins managing a large number of collections to be able to filter collections.

**Comment by weiweishi** [comment]
@pgwillia I think we can help with @sfbetz's issue with a filter to
distinguish files and communities/collections on the search result page.
I'm not sure if this related to the resource types on collections?

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by pbinkley** [comment]
Will reconsider after PCDM and Peel are in focus.
