### ISSUE TITLE
Rebase ARK feature branch on master

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#1170]
The ARK feature branch was previously merged into master (#973) and then reverted on March 9 (c2f52b5). It needs to be brought up to date so that it can be remerged.

**Comment by weiweishi** [comment]
Bugs discovered after rebase:
- [ ] Ark is not created on new objects

**Comment by weiweishi** [comment]
@mbarnett @pgwillia I want to run this change with you:
On the ark_feature_branch, I've confirmed that Chris' code failed because he had the ezid creation prior to the file.save, and generic file wouldn't have a noid until it's saved, so the ezid creation process would fail. https://github.com/ualbertalib/HydraNorth/blob/f31db7ce38ccf23c3d51da5a0fca06c1a6aae1a5/app/jobs/batch_update_job.rb#L80-L92

I moved the code https://github.com/ualbertalib/HydraNorth/blob/07d2ffa8ad1eeb22112378eb1796a37bbb15bf7a/app/jobs/batch_update_job.rb#L78-L93
But this also means that we need to save the file twice during upload, which means it will affect performance, although this process is handled by Resque, so it's less impact to the overall user experience. 
Do you see an issue with this change? And do you think there's a better way to handle this situation?

**Comment by mbarnett** [comment]
I haven't entirely tried or tested this, but based on a few minutes of looking at ActiveFedora and Sufia, I *think* you can do this and save a call to ```save```

```ruby
    gf.id = gf.assign_id
    Sufia.queue.push(ContentUpdateEventJob.new(gf.id, login))
    ezid = Hydranorth::EzidService.new()
    begin
      ark_identifier = ezid.create(gf)
    rescue Ezid::Error
      ark_identifier = ezid.find(gf)
    end

    unless ark_identifier.nil?
      gf.ark_created = "true"
      gf.ark_id = ark_identifier.id
    else
      gf.ark_created = "false"
    end
    save_file(gf)
```

Assign ID comes from ActiveFedora (overridden by the Noid gem). Calling ```assign_id``` mints a noid, so we don't want to be wasting millions of them, but I think it should be fine here. ActiveFedora should respect the fact that the GenericFile already has a noid when it saves it, and not mint another one and overwrite it (but you'll want to test that to make sure I'm reading the code right)

**Comment by weiweishi** [comment]
It turns out that the problem lies elsewhere - it's the mapping of the resource_type, which is not complete. The metadata creation doesn't handle empty string well. (The stacktrace made me believe it's an empty string of the id, and my tests with a different resource type made me believe I was on the right track. sorry for the few minutes you spent on this @mbarnett )
 
@johnhuck, 
Here is our current mapping from Hydranorth resource_type to DataCite resourcetype:
  config.ark_resource_types = {
    "Book" => "Text/Book",
    "Book Chapter" => "Text/Chapter",
    "Conference\/workshop Poster" => "Image/Conference Poster",
    "Conference\/workshop Presentation" => "Other/Presentation",
    "Dataset" => "Dataset",
    "Image" => "Image",
    "Journal Article (Draft-Submitted)" => "Text/Submitted Journal Article",
    "Journal Article (Published)" => "Text/Published Journal Article",
    "Learning Object" => "Other/Learning Object",
    "Report" => "Text/Report",
    "Research Material" => "Other/Research Material",
    "Review" => "Text/Review",
  }

Could you please:
1. review if this mapping is correct?
2. advise how we should map special reports like computing science technical reports and structuring engineering reports (Text/Report?)
3. advise how we should map theses?

Thanks!

Weiwei

**Comment by johnhuck** [comment]
Hi @weiweishi , sorry I missed the message earlier. Yes, those are correct (Should I assume the backslashes are escape characters in "Conference\/..." etc.?). I'm reposting my mapping documents to this thread, which were on #571 and contain the other mappings, but briefly, 

2. Text/Report
3. Text/Thesis

Sheet in the Hydra North Data Dictionary (Summary with final instructions/recommendations):
https://docs.google.com/spreadsheets/d/1hSd6kf4ABm-m8VtYNyqfJGtiZG7bLJQ3fWRbF_nVoIw/edit#gid=1902267812 

More detailed process document:
https://docs.google.com/spreadsheets/d/1JZ702gTPHQxMIVPSRlb_M8LFRhpYqHFZuFxAMlLP-rE/edit#gid=1437364723

**Comment by weiweishi** [comment]
Thanks @johnhuck for the clarification and the additional documentation. I will proceed on this basis.
