### ISSUE TITLE
CCID-protected thumbnails do not show in search results for CCID users

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#1194]
Seems to be a problem with detecting CCID-protection via ```document.institutional_access``` [here](https://github.com/ualbertalib/HydraNorth/blob/754f2f4382b98007f5f007ebf76b3e6dd784d0d0/app/helpers/sufia_helper.rb#L15)

**Comment by pgwillia** [comment]
The present logic gives the default thumbnail for all documents with institutional_access. What we actually want is to display the thumbnail if the user ```can? :download GenericFile.find(document.id)```. 

So there are a couple of challenges with this. 
* this will revise the N+1 queries for search results because we need the generic object in order to know it's permissions
* I'm having trouble setting up the spec for this because I need to create a user with abilities and I can't figure out what's returning nil for authenticate! to mock it.

Anyone have thoughts or suggestions?

**Comment by pgwillia** [comment]
Realized that I might be able to monkey patch like @mbarnett did in https://github.com/ualbertalib/HydraNorth/commit/bfebfe99205d9797a1f6d64aa6284077ab516bbe to be able to do this with just the SolrDocument (thanks for the idea @piyapongch). That would mean that calls to Fedora would not be necessary and no performance hit. I'll give it a try...

**Comment by pgwillia** [comment]
Hmmm. ```cannot?(:download, document)``` where document is a SolrDocument always returns false, I think because our rule is ```can :download, GenericFile do |obj|```

Do I try to cast document, or change the rule?

**Comment by mbarnett** [comment]
Maybe a second rule for SolrDocuments?
