### ISSUE TITLE
Remaining work for collection related issues 

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#1205]
This is an issue to amalgamate works left on several collection/community related issues #909 #961 #962 #786, and additional bugs discovered on collection/community page. 
As admin:
- [ ] When I creates a new collection, I want to be able to choose a community to add it to. (Currently can't be done at the time of collection creation, but can be added from the dashboard/My Files & Collections) - **Need to be alphabetized (should be done #909, need to be verified with more test data)**
- [ ] Allow admin to remove nested collections or objects from parent community - **low priority**
- [ ] Allow admin users to edit objects/collections from the action menu on collection page. - **will not fix**
- [ ] Details on collection page doesn't show proper information for nested collections.  - **low priority**
  ![screenshot - 16-06-24 - 12 57 02 pm](https://cloud.githubusercontent.com/assets/2047614/16347656/28478704-3a0b-11e6-89dc-c3e2b651a907.png)

As a regular user:
- [ ] No search box available for the community page - **low priority for now, and will reevaluate with Hydranorth 7** 
- [x] Community page now shows both objects and collections, but the long-term requirement is to have community page only display collections, as all objects should belong to a collection. 
- [x] Only 10 objects showing on the collection page. #1207 
  @sfbetz anything you cares about fixing?

**Comment by sfbetz** [comment]
Based on our original rationale for these requirements, here are my thoughts (would also like @leahvanderjagt to jump in if anything seems out to lunch!):

-Collection nesting into communities is necessary, but doesn't have to happen directly from the collection creation stage. The alternative approach (from dashboard) will work as long as the collections and communities are alphabetized both in dashboard and in popup window, so admin can find the correct collections to associate.  However, right now, they are not ordered, so finding the collection in a list of 400 is very difficult. Also this bug (#865) makes sorting the collections list by most recently created, or seeing more than 10 items / page impossible. 
-We can manage objects directly from their edit form, so will be able to place them in any community / collection that way. 
-Removing collections from communities is less frequent activity, and can happen through the back end, so I think we would be okay with this being low priority. 
-Objects / collections can all be managed through their edit pages (via search) so I think we would be okay with this also being low priority. 
-Details on collection page will only display to admin user, so am okay with this being low priority.
-Right now "search this collection" is appearing at collection level, but not at community level: the search at community level was only searching titles of collections, rather than items in collections, so had very limited value and was misleading. I think we decided the ROI was too low to pursue developing this function.
