### ISSUE TITLE
OAI error in pdf links: noid is missing

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#1226]
The OAI stylesheet needs to be adjusted. It currently produces pdf links like this:

```
https://era.library.ualberta.ca/files/<filename>
```

Which should be like this:

```
https://era.library.ualberta.ca/files/<noid>/<filename>
```

(This is from memory since the test server is currently not generating pdf links at all.)

**Comment by piyapongch** [comment]
The download link should show up only on thesis item
(metadataPrefix=oai_etdms) and the link should be in format,
https://era.library.ualberta.ca/downloads/fileName.pdf. The fileName.pdf
comes from model:downloadFilename property. #972



Piyapong.

**Comment by anayram** [comment]
Issue #971 describes the general requirement for resolvable identifiers in the format `<dc:identifier>http://era.library.ualberta.ca/files/noid</dc:identifier>`
The requirement for a resolvable identifier was implemented as landing pages for all metadata formats.
From https://era-test.library.ualberta.ca/oai?verb=ListRecords&metadataPrefix=oai_dc
I get:
```xml
<dc:identifier>https://era.library.ualberta.ca/files/44558d306</dc:identifier>
```

The pdf links came in as an extra LAC requirement. LAC only wants pdf links in the oai_etdms feed, so I think that is why you can only see pdf links in that format and not as oai_dc.
From https://era-test.library.ualberta.ca/oai?verb=ListRecords&metadataPrefix=oai_etdms
I get
```xml
<etd_ms:identifier>
https://era.library.ualberta.ca/downloads/NQ39561.pdf
</etd_ms:identifier>
```

Noids are missing from pdf links, though, so that needs to be fixed.

**Comment by anayram** [comment]
Quick follow-up--pdf links are handled in @piyapongch's code (the stylesheet handles namespaces and schema declarations and leaves the data untouched).

**Comment by pbinkley** [comment]
The proper download link syntax is now
https://era.library.ualberta.ca/files/<noid>/<filename> - this is the way
the links are presented on ERA since the we deployed Hydranorth 1.3 on the
weekend. We need to update the OAI server to generate links in this format.
I think this should be an easy change to the stylesheet.

**Comment by anayram** [comment]
I added this to the stylesheet but it looks like @piyapongch also added it in his code where he handles identifiers. The server now throws a 502 error, though.

In case it is still useful here is the stylesheet.
[metadata.xsl.tar.gz](https://github.com/ualbertalib/HydraNorth/files/400276/metadata.xsl.tar.gz)

**Comment by anayram** [comment]
Closing this issue. See #972
