### ISSUE TITLE
Streaming links in ERA (IR) are no longer working

### ISSUE THREAD

**Issue by leahvanderjagt** [ualbertalib/HydraNorth#1244]
As a user I expect the streaming links for a/v content in ERA (IR) to stream the file so that I don't have to download the item.

From email w/Matt

At a quick glance, it looks like this was broken by https://github.com/ualbertalib/HydraNorth/commit/68e357c052a9d19468b5731523e5af046d027902.

eg) https://era.library.ualberta.ca/files/zp38wg46r#.Vw0c2xMrKL4 contains an audio tag with <source src="/downloads/zp38wg46r?file=mp3" type="audio/mpeg"> but /downloads/zp38wg46r?file=mp3 redirects to /files/, and loses the format parameter in the process.

**Comment by mbarnett** [comment]
With the reindex for title sorting complete, we can also re-enable download links on search result pages with DOI links handled properly (aka #1098). The same change that broke this turns out to have broken the download links when I re-enable them, so I'm going to clean up both issues now so that we can get title sorting and the download links restored in the next release. /cc @pbinkley
