### ISSUE TITLE
Spike: Improve our search results in Google

### ISSUE THREAD

**Issue by leahvanderjagt** [ualbertalib/HydraNorth#1260]
-Work to improve search results in Google (not Google Scholar)

-Set up a Google Sitemaster instance for ERA

**Comment by pgwillia** [comment]
Should be able to get some useful information from [Google Search Console](https://www.google.com/webmasters/tools/home?hl=en).  @weiweishi and others with access to Google Analytics could set this up.

**Comment by pgwillia** [comment]
Lots of good stuff here! I submitted our sitemap.
![screenshot from 2016-09-26 13-36-00](https://cloud.githubusercontent.com/assets/1220762/18849060/665484b6-83ee-11e6-9263-a433c0e75bfa.png)

**Comment by leahvanderjagt** [comment]
Possibly related to #906 , we need to see if there is more work to do checking for ERA indexing in google and for any easy wins. @pbinkley @mbarnett @weiweishi, can you please review this ticket?

**Comment by mbarnett** [comment]
Thoughts after spending an hour looking into this:

### Google Search Console-related:

- The sitemap was submitted for https, but apparently not for http. We should submit it for both.

- Google reports that there are errors reported for our sitemap which we should fix:
```Invalid XML tags:

Sitemap: era.library.ualberta.ca/sitemaps/sitemap-fragment-1.xml
Parent tag: urlset
Tag: md

Sitemap: era.library.ualberta.ca/sitemaps/sitemap-fragment-1.xml
Parent tag: url
Tag: md

Sitemap: era.library.ualberta.ca/sitemaps/sitemap-fragment-1.xml
Parent tag: url
Tag: ln
```

- We should fix particularly slow response time pages that the crawler noted (there are 19 instances noted, with examples http://era.library.ualberta.ca/files/bd217qp64s, http://era.library.ualberta.ca/files/jd472w951, http://era.library.ualberta.ca/files/v692t7312)

- Fix a number of broken items linked in the sitemap (example: https://era.library.ualberta.ca/files/th83m176r). 

- Fix duplicate titles (Google notes about 3000 pages with this issue, see the HTML improvements tab in the search console).

- More Generally: We should *establish who should be responsible for monitoring this on a regular basis*, because these errors have been sitting here for months with no one monitoring the tools Google gives us to keep track of this stuff. I do not know off-hand if there is an API we could use to get this into the Sysadmin team's monitoring.

### Non-Search Console related:

- Clean up pagination: https://moz.com/blog/seo-guide-to-google-webmaster-recommendations-for-pagination
Robots.txt disallows on catalog, but we should  be Noindexing collection pages 2 through N, for instance

- Improve titles on generic file pages: (eg. title tag is just "ERA" here) https://era.library.ualberta.ca/files/ck3569453q. It should probably be something more meaningful, like "Model Based Control of Combustion Timing and Load in HCCI Engines - ERA".

- Fix spurious port appearing in loc in sitemap https://era.library.ualberta.ca/sitemaps/sitemap-fragment-1.xml: <loc>http://era.library.ualberta.ca:443/</loc>

- Do something smarter with priorities (probably want higher on file pages, lower on collections, not blanket "1")

I'd say there's at least a couple of sprints there, in total, and that's without really digging into more SEO-oriented things we could pursue. We need to figure out some priorities for this work versus everything else we have on our plates, as it's currently competing with the Sufia 7.2 work, the preservation work, and the Plugin WG commitments we have.

**Comment by leahvanderjagt** [comment]
I think we should reduce or nearly eliminate that competition by
implementing this work for Sufia 7.2. If there's anything REALLY easy then
it would be great to do that now, but otherwise, for now, I'm not tearing
my hair out over this so we can wait.

___________________________________________________________




*Leah VanderjagtDigital Repository Services Coordinator University of
Albertat. 780.492.3851 *
*leahv@ualberta.ca <leahv@ualberta.ca> *

**Comment by pbinkley** [comment]
Ready for decisions about work to be done.
