### ISSUE TITLE
DOI Unavailable

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#1283]
- [ ] Based on output of #1280 
- [ ] Handles the state change of DOI. (unavailable)
- [ ] Set [status message](http://ezid.cdlib.org/doc/apidoc.html#identifier-status) (reason for the object's unavailability) in EZID (To provide information on the registry)

**Comment by pgwillia** [comment]
#1276 
There are two cases for unavailable: deleted items and private items.
Both should set ```_export=no```

**Comment by johnhuck** [comment]
From @leahvanderjagt and @sfbetz, the status message for private items should be "not publicly released"

**Comment by johnhuck** [comment]
I can now confirm that we recommend using the :erc code `:unal` , which means "unallowed; intentionally suppressed" in place of a value for each of the required metadata elements when registering private items as with a DOI status of "unavailable."

When an item is marked "unavailable" because it is deleted, however, the metadata in its last public state should be maintained. That is, if the item were public, it should retain normal metadata, as a guide to people who may have the DOI. If the item were private before it was deleted, though, the `:unal` codes should be retained, since we don't want to advertise its identity after the fact.

Please note that this code is different from the :erc code `:unav` ("unavailable; possibly unknown") which we have recommended using for normal items that lack a four digit year of publication.

The status message to accompany the chance in status to unavailable for private items should be "unavailable | not publicly released".

For deleted items, I am going to recommend "unavailable | withdrawn" .

Let me know if there are any other questions I can help with. Cheers!
