### ISSUE TITLE
9.1 a Metadata in generic file form

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#129]
As a user, I want to be able to describe my deposited generic file according to ERA norms to enable discovery and reuse as part of #30 
- Metadata team will provide specs on needed changes with examples to existing Sufia forms

 - [x] have forms with all of the fields needed to describe the items
 - [x] stored properly in Fedora, indexed and searchable properly in Solr,
 - [x] integrate with external ontology e.g. geo names

**Comment by weiweishi** [comment]
View test is done in Selenium / with spec-views. Right now tests have to be run through workstation, as there's no headless firefox installed on the VM. This should not be a problem in the future when we integrate the tests in Jenkins. 
To run the tests, pull the repository directly to your workstation, run bundle install, and then run the tests by 
bundle exec rspec spec-views.

**Comment by pbinkley** [comment]
It takes only a few steps to install headless Firefox on CentOS:
http://maxivak.com/running-selenium-tests-with-ruby-on-centos/#codesyntax_2
(he left out steps of changing the YOUR_USER in the init script to a real
one, e.g. apache, and of creating the log directory /var/log/xvfb belonging
to that user). Would it be worth adding this to the playbook, so selenium
testing is available to devs all the time? The fewer impediments to testing
the better, but I don't know whether it would strain the VM environment to
run this extra service. And I haven't actually tested that it works since I
don't have a Selenium test handy.

Peter

Peter Binkley
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by weiweishi** [comment]
We went back and force on this when we first set up tests for DMP tool.
There was problem with FF version etc and it felt it took too much time to
figure out these issues. So we decided to do it with this alternative
solution. But things may have changed and  I should try again and see if
everything works now.

**Comment by pbinkley** [comment]
This seems to serve Selenium tests both for Travis and locally:

http://docs.travis-ci.com/user/gui-and-headless-browsers/

I'll see if I can get it working.

**Comment by weiweishi** [comment]
Thanks!
