### ISSUE TITLE
Fix format of DOI link on item page

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#1312]
"Permanent Link (DOI):" should be the label, i.e. outside the anchor. The link should be just the DOI.

**Comment by johnhuck** [comment]
I know that there has been ongoing discussion about how to display the DOIs and I don't wish to interpose myself and interfere with those decisions, but some greater precision about our terminology might not be a bad thing to clarify what we want to show. I was going to jump in on #1284 but it seemed unnecessary at the time.

A 'DOI name' (the closest thing to 'the DOI') takes the form `doi:10.10.123/456`. When embedded in a URL for the proxy server, it looks like this `http://doi.org/10.123/456`. Note that the `doi:` prefix in the name, which is an integral part of the DOI name is not present in the proxy URL. So do we want to display the DOI name which anchors the proxy URL, or display the proxy URL? It's perfectly fine if we want to display the URL. Some citation style guides recommend or allow it, I think. Just a question of being clear about what we want.

Other information useful to know: The [DOI handbook](http://www.doi.org/doi_handbook/3_Resolution.html#3.8) indicates that for the proxy servers, http://doi.org is preferred, but http://dx.doi.org is acceptable too, and that they responds to both http and https requests.

**Comment by sfbetz** [comment]
To clarify, the spec for display is that the url (and how the url is displayed in the top left area) should look like this: https://doi.org/10.1629/22161

So (expressed in basic HTML) this is what we want to happen:

`Permanent link (DOI): <a href="https://doi.org/10.1629/22161">https://doi.org/10.1629/22161</a>`



CrossRef (a major DOI registration agency) has updated their documentation to drop the .dx from the DOI url. This will become the new standard for published article DOIs, so one we should probably follow as well.

**Comment by johnhuck** [comment]
Thanks for clarifying, @sfbetz. Good to be following CrossRef practice, for sure.

I checked ISO 26324, which is the normative reference for DOI syntax and clarified my own understanding of the terminology, and I was wrong on one important point. For your interest: the DOI name, in fact, consists only of the prefix and suffix (e.g., 10.1629/22161). I was wrong about the label `doi:` being integral to the identifier. Its purpose is to render the DOI name as a valid (albeit non-http) URI. So the full DOI name is, in fact, appended to the proxy server URL address, and it is also therefore a URI, and the ISO standard confirms this as an alternate form of presentation.

It seems like a silly detail, but the reason I was attending to this was because I was concerned there was a potential mismatch between our custom metadata field 'doi' and a URL that was not in fact a DOI. But that was based on my false understanding that the `doi:` label was integral. Now that I have a better understanding of the syntax, I can say confidently that this is not a problem. Carry on!
