### ISSUE TITLE
Enable Google Analytics

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#252]
Investigate whether we can enable GA on hydranorth.library.ualberta.ca, so that the download and view counts will appear on the analytics page for items as a demo of that functionality.

Question: will Google enable Analytics on a site that is closed to the public?

**Comment by pgwillia** [comment]
https://github.com/projecthydra/sufia#analytics-and-usage-statistics

**Comment by pbinkley** [comment]
If you learn anything that might be useful to #210, please put it in a comment there.

**Comment by pgwillia** [comment]
I can enable Google Analytics on a site that is closed to the public.  I couldn't get it to work on hydranorth.local, but changing my VM hostname to be hydranorthdev.library.ualberta.ca is collecting statistics.

**Comment by pgwillia** [comment]
I think that this should be configured on test and prod but that the default on development should be to leave this unconfigured and untested because:
* would require anyone using HydraNorth off github to configure Google Analytics (GA) before tests would pass (including CI servers)
* configuration requires google_analytics_id which maps to a single url.
 * stats reported from development environment would be confusing if shared, time consuming to configure if individual
* oauth configuration contains secrets which shouldn't go in version control
* feels like a configuration management problem

What do others think? Meanwhile, I'll start working on a patch for the playbook.

**Comment by pgwillia** [comment]
I've got the users to add to the GA account.  Who should be able to access the Google Developers Console Project to manage the API access and settings for the Google+ and Analytics APIs as well as the Service Account OAuth client ID?

**Comment by pbinkley** [comment]
I think the dev team would be fine for that. Access to the dashboard should
be the same as for current ERA.

Peter

**Comment by weiweishi** [comment]
GA not on dev sounds reasonable to me. We should also look into exclude the
traffic from CI servers to test/production instances.

All the hydranorth dev team (all developers/Peter/me) should have access to
it? And we can add more people (system admins/Sam etc) if needed in the
future?

Weiwei

**Comment by pgwillia** [comment]
Completed.  Hydranorth dev team has edit access. Did not investigate excluding CI traffic.
