### ISSUE TITLE
date_created - which metadata field I should use in migration

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#266]
I used dcterms:created for date_created. But it seems it's not always presented. 
There's dateaccepted and datesubmitted but don't think they are what we are looking for.

**Comment by pbinkley** [comment]
dcterms:created is right for the user-supplied publication date; the other two are system-supplied process dates. If dcterms:created is absent, we don't have a date in the bibliographic metadata, so we should leave it out in HydraNorth. But does its absence cause any problems?

**Comment by sfarnel** [comment]
we know that some items that do have a date in the citation field did not
have it entered into as a discrete date element. these will be fixed as we
move through collections in time for production launch. some but not all
will be fixed by soft launch. the system will need to be able to handle
this circumstance as there may well be valid cases for no date of creation.

On Wed, May 13, 2015 at 11:19 AM, Peter Binkley <notifications@github.com>
wrote:

> dcterms:created is right for the user-supplied publication date; the other
> two are system-supplied process dates. If dcterms:created is absent, we
> don't have a date in the bibliographic metadata, so we should leave it out
> in HydraNorth. But does its absence cause any problems?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/266#issuecomment-101750983>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by weiweishi** [comment]
Thanks to you both. The system is able to handle empty date_created field,
so won't be any issue there.

**Comment by weiweishi** [comment]
Dealt with in PR #292
