### ISSUE TITLE
9.4 Only Admin Users can Delete

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#33]
As admin, I want to be the only user to delete items from Hydra North

Done: 
- [ ] admin can delete any items
- [ ] no non-admin can delete an item

**Comment by criedlberger** [comment]
This issue has been put on hold due to enhancements to Fedora 4. See topic:

https://groups.google.com/forum/#!topic/hydra-tech/aebxwzlrEl8

**Comment by pgwillia** [comment]
This will not be implemented in Fedora 4.

**Comment by pgwillia** [comment]
Users in ERA cannot delete.  Depends on answers to audits.

**Comment by pbinkley** [comment]
One more thing: remove the "Delete" button from the dropdown menu for files for regular users.

**Comment by sfarnel** [comment]
In current ERA a user can't delete an item, even one they own. Related to
this, in current ERA an item can be 'deleted' which meant it was simply
made inactive but then actually had to be 'purged' in order to completely
delete it. There have been cases with ERA when something had to be
recovered.

If I recall, Sufia has (or had; we may have added additional functionality)
a single functionality, i.e., when something was 'deleted' it was really
and truly gone.

So I think this was a combination of not wanting people to accidentally
'delete' something that we couldn't get back if necessary and close
approximation of current ERA functionality.

On Fri, Sep 4, 2015 at 9:02 AM, Weiwei Shi <notifications@github.com> wrote:

> Sorry for bring up such an old ticket, but I am just wondering what was
> the logic to not allowing users to delete GenericFile even if they are the
> owner (except theses objects)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/33#issuecomment-137760239>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685
