### ISSUE TITLE
Metadata - URIs for strings phase 1: item type, language, license

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/HydraNorth#370]
As the metadata team, we would like to have the objects of select metadata triples - item type, language, license - stored as URIs but displayed to the user as strings so that our data will be interoperable with other linked data.

**Comment by pbinkley** [comment]
Forms within HydraNorth do not yet deal with the parallel values (URI and display value)
- does Questioning Authorities deal with this? Instead of storing the display value we would retrieve it in real time. (Primary use case is autocomplete rather than display, so performance might be an issue for display). 
- we therefore need a spike to investigate: does Questioning Authority meet this need? Or is it better to simply maintain two values (URI and display), based on a controlled vocabulary? The spike is to compare these approaches (for performance and management) 
- criteria: acceptable level of performance in display (should be imperceptible); complexity of implementation
- timebox this at two days for the spike

**Comment by weiweishi** [comment]
https://wiki.duraspace.org/display/hydra/Descriptions+of+current+RDF+practice

**Comment by sfarnel** [comment]
From what I've seen there doesn't seem to be much consensus in the broader
LOD community around storing URIs, strings, or both, so I think we're in
fine shape either way.

On Fri, Jun 12, 2015 at 1:53 PM, Weiwei Shi <notifications@github.com>
wrote:

>
> https://wiki.duraspace.org/display/hydra/Descriptions+of+current+RDF+practice
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/370#issuecomment-111574463>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by sfbetz** [comment]
@leahvanderjagt @sfarnel to meet with metadata team to help assess priorities for this group of issues

**Comment by pbinkley** [comment]
This issue was moved to ualbertalib/Hydranorth2#115

**Comment by pbinkley** [comment]
This issue was moved to ualbertalib/Hydranorth2#116
