### ISSUE TITLE
Metadata - Download of citations for items in new ERA

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/HydraNorth#423]
As the metadata team, we would like to ensure that users get complete and accurate citations for items in new ERA so that they can provide proper attribution for items as needed.

- [ ] review metadata profiles for citations and revise as needed

**Comment by johnhuck** [comment]
Of the three citation export formats (Endnote, Zotero, and Mendeley), Endnote seems to be the one that it is possible to adjust, via a mapping file (https://github.com/projecthydra/sufia/blob/master/sufia-models/app/models/concerns/sufia/generic_file/export.rb). The other two options appear to look only at metadata embedded in objects (i.e., mainly PDFs).

Message when you click on Export to Zotero:
"Exporting to Zotero is supported via embedded metadata. If Zotero does not automatically pick up metadata for deposited files, please report the issue via the Contact Form." 

Message when you click on Export to Mendeley:
"Exporting to Mendeley is supported via embedded metadata. If Mendeley does not automatically pick up metadata for deposited files, please report the issue via the Contact Form."

After examining representative examples of various types of ERA items, here are some observations. All items had:

%T' => [:title, ->(x) { x.first }],
%A' => [:creator],
%D' => [:date_created],
%8' => [:date_uploaded],
%R' => [:persistent_url],
%X' => [:description],
%G' => [:language],
%[' => [:date_modified],
%9' => [:resource_type],
%~' => I18n.t('sufia.product_name'),
%W' => I18n.t('sufia.institution_name')

Some had:
%E' => [:contributor],

The following fields were always present, even when they were blank. Whether this is due to obligation constraints applied in HydraNorth or due to Endnote obligations is unclear.
%D' => [:date_created],
%X' => [:description],

%D' => [:date_created] appears as "Year" in Endnote, and is used in the citation.

%8' => [:date_uploaded] and %[' => [:date_modified] are timestamp dates of the form: 2014-10-20T16:48:02.763+00:00. Endnote records them, but does not use them in the citation, even when there is no value for "Year."

The value for %~' => I18n.t('sufia.product_name') is "ERA," which displays as "Database Name" in Endnote. The name could perhaps be given in a more complete form so it is meaningful outside of its original context.

The value for %W' => I18n.t('sufia.institution_name') is  University of Alberta, which displays as "Database Provider" in Endnote.
