### ISSUE TITLE
SAML Authentication

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#428]
Modelled on DMP

**Comment by pgwillia** [comment]
Story: SAML
As a University of Alberta user with a valid CCID, I want to use these credentials to login to ERA so that user doesn't have to remember a separate username/password.

Scenario 1: Sign in, doesn't have user account, can use SAML credentials to login
Given user has valid CCID/password
And user visits /users/sign_in
When they click on "Sign in with Shibboleth"
And enter their SAML credentials
Then an ERA account should be created
And that user should be signed in
And that user should be redirected to /

Scenario 2: User has existing user account, link account to SAML credentials
Given user has valid CCID/password
And user is logged into their existing ERA account
And the user edits their profile
![image](https://cloud.githubusercontent.com/assets/1220762/8164980/fb977374-1349-11e5-9388-789666e9fa4a.png)
When they click "Link to CCID"
And enter their SAML credentials
Then their ERA account should be updated to include shibboleth_id
And that user should be signed in
And that user should be redirected to /user/:id
![image](https://cloud.githubusercontent.com/assets/1220762/8165127/104da864-134b-11e5-9160-ce666a9be480.png)
And future visits to the profile should reflect that the link exists
![image](https://cloud.githubusercontent.com/assets/1220762/8165007/2dea2056-134a-11e5-856a-a17aba80a37e.png)

Scenario 3: Sign up, doesn't have user account, sign in with SAML
Given user has valid CCID/password
And user visits /users/sign_up
When they click on "Sign in with Shibboleth"
Then they are presented with Scenario 1

Scenario 4: User is challenged for credentials, has user account, SAML sign in success, is redirected to protected target
Given user has valid CCID/password
And user visits /files/new
When they click on "Sign in with Shibboleth"
And enter their SAML credentials
Then that user should be signed in
And the user should be redirected to /files/new 

Scenario 5: Sign in, has user account, sign in failure
Given user has valid CCID/password
And SAML connection has issue
When user tries to "Sign in with Shibboleth"
Then should prompt that "There is a problem with the service, try again later."

Scenario Edge Cases: Sign in, has user account, sign in failure
* invalid CCID: handled by IST
* invalid/forgotten password: handled by IST
* should users be able to confirm accounts created using SAML only?
* should users also be able to login using email/password with accounts created using SAML only?
* should users be able to continue to login using email/password with accounts linked to CCID?

**Comment by pbinkley** [comment]
Question for Amanda and Geoff: if Shibboleth returns a different email address than what the user provides, do we automatically update the user record in Hydra North? We think no.

**Comment by pbinkley** [comment]
Further question: if I create a Hydra account as peter.binkley@ , and U of A Shibboleth returns pbinkley@, what do we do? We need information from IST and experience with U of A Shibboleth to resolve this.

**Comment by pbinkley** [comment]
Further question: should we use EPPN to discover whether there is already an account linked to this CCID? Do we allow more than one Hydra account to link to a single CCID?

**Comment by pgwillia** [comment]
![20150622_151724](https://cloud.githubusercontent.com/assets/1220762/8293420/81592946-18f2-11e5-9146-122af757ab2a.jpg)

**Comment by pgwillia** [comment]
In conversation with IST help desk:
```
Janet Kwan:Hello Tricia, both CCIDs and Email aliases may be reused, after they have expired for a period (at least 1 year, but not sure when exactly)
15:35
Janet Kwan:A person's ID number will never be reused
```

**Comment by pbinkley** [comment]
Thanks, Tricia. This suggests we need a long-term strategy for freezing
HydraNorth accounts when a user leaves the university and thereby makes
their CCID available for recycling. The same would apply to other services
where we manage user content based on CCID (DMP Builder, Dataverse).

Peter Binkley, Ph.D., MLIS
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by sfbetz** [comment]
Needs to be broken down into some smaller more manageable pieces.
