### ISSUE TITLE
Google Scholar indexing

### ISSUE THREAD

**Issue by awakaruk** [ualbertalib/HydraNorth#435]
Story: 
As a researcher I want my colleagues to find the articles I deposited in ERA via a Google Scholar search. 

Note: best practices for maximizing repository indexing are noted in an OR 2015 presentation by Anurag Acharya here: http://www.or2015.net/wp-content/uploads/2015/06/or-2015-anurag-google-scholar.pdf

**Comment by sfbetz** [comment]
This is a high priority issue for discovery and access to the content of ERA. Some discussion about Google Scholar on Hydra Community list:
https://groups.google.com/forum/#!searchin/hydra-community/google$20scholar/hydra-community/oOmTMIZ5bZ0/HQM1XAKGw8IJ

Right now some ERA content is being successfully indexed by GS  (about 5690 titles) https://scholar.google.ca/scholar?hl=en&q=site%3A.era.library.ualberta.ca&btnG=&as_sdt=1%2C5&as_sdtp=

I don't know what will happen to these citations now that we've migrated.

**Comment by pbinkley** [comment]
If you sort by date instead of citation count you find that some of our
indexed items have no citations known to Google, so presumably they were
harvested from the site rather than just being picked up from citations. We
changed our url structure in old ERA to suit Google's wishes (see
https://docs.google.com/document/d/1t8LMGsYEQtkvWOSGHLXJDGJ-8fLVPgumrBqwWHQjkMY/edit#heading=h.xa6tnyj5zdye
, "Implications for ERA", point 1), and I think that helped. There is
probably more we could do:

- Sufia doesn't have sitemaps
- implement the year/month browse for recent items

But this work is hard to prioritize when there's no way to tell whether
it's having an effect on Google's harvesting.

**Comment by sfarnel** [comment]
Definitely worth a larger conversation now that we have content moved over.

On Thu, Oct 22, 2015 at 1:49 PM, Peter Binkley <notifications@github.com>
wrote:

> If you sort by date instead of citation count you find that some of our
> indexed items have no citations known to Google, so presumably they were
> harvested from the site rather than just being picked up from citations. We
> changed our url structure in old ERA to suit Google's wishes (see
>
> https://docs.google.com/document/d/1t8LMGsYEQtkvWOSGHLXJDGJ-8fLVPgumrBqwWHQjkMY/edit#heading=h.xa6tnyj5zdye
> , "Implications for ERA", point 1), and I think that helped. There is
> probably more we could do:
>
> - Sufia doesn't have sitemaps
> - implement the year/month browse for recent items
>
> But this work is hard to prioritize when there's no way to tell whether
> it's having an effect on Google's harvesting.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/435#issuecomment-150336472>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by johnhuck** [comment]
We will start to add specific problems around Google Scholar indexing to this issue.

First off, it appears that we have to revisit the three items in Implication 1 in our original Google Scholar Strategy document: "We must modify download urls to include the “.pdf” and use the DS1 label, and put pdf in same subdirectory as landing page"

https://docs.google.com/document/d/1t8LMGsYEQtkvWOSGHLXJDGJ-8fLVPgumrBqwWHQjkMY/edit#

**Comment by johnhuck** [comment]
Here is an example of the markup with Highwire Press tags that is already present in new ERA html. Note the tags that 'sufia does not yet support', due to the sufia metadata configuration. 

	
	  <meta name="citation_title" content="Multiple-complete-digest restriction fragment mapping: Generating sequence-ready maps for large-scale DNA sequencing"/>
  <meta name="citation_author" content="Wong, Gane K."/>
  <meta name="citation_author" content="Yu, Jun "/>
  <meta name="citation_author" content=" Thayer, Edward C."/>
  <meta name="citation_author" content="Olson, Maynard V."/>
  <meta name="citation_publication_date" content=""/>
  <meta name="citation_pdf_url" content="http://era.library.ualberta.ca/downloads/bsj139193r"/>
  
  

The code that generates these tags I believe is found here:
https://github.com/projecthydra/sufia/blob/fa0190067b76f825d2e017ceb1dca7fb95cbe250/app/views/generic_files/show.html.erb

**Comment by sfarnel** [comment]
Hmm, maybe something we could contribute back to the community?

On Fri, Nov 13, 2015 at 1:45 PM, johnhuck <notifications@github.com> wrote:

> Here is an example of the markup with Highwire Press tags that is already
> present in new ERA html. Note the tags that 'sufia does not yet support',
> due to the sufia metadata configuration.
>
> 
>   <meta name="citation_title" content="Multiple-complete-digest restriction fragment mapping: Generating sequence-ready maps for large-scale DNA sequencing"/>
>
>
>
>
>
>
>
> 
> 
>
> The code that generates these tags I believe is found here:
>
> https://github.com/projecthydra/sufia/blob/fa0190067b76f825d2e017ceb1dca7fb95cbe250/app/views/generic_files/show.html.erb
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/435#issuecomment-156551966>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by weiweishi** [comment]
3600+ items currently indexed in Google Scholar as of Dec 7, 2015 before the implementation of url changes and sitemap. The plan is to implement #848 and #849 with sitemaps to see what kind of improvement we can get. (will include screenshots through the process)

**Comment by sfbetz** [comment]
Current state of google scholar site search:
![screen shot 2015-12-09 at 2 04 29 pm](https://cloud.githubusercontent.com/assets/12801010/11698823/0a4528fc-9e7e-11e5-8b67-58f3a39ffb69.png)

**Comment by sfbetz** [comment]
Current state of Google scholar search is now extra depressing: as of today they are indexing a total of 46 results. Urgh...

**Comment by gsharder** [comment]
I thought we were at 3600+ items being indexed in December. Any idea why
the change?

On Fri, Jan 8, 2016 at 3:35 PM, Sonya Betz <notifications@github.com> wrote:

> Current state of Google scholar search is now extra depressing: as of
> today they are indexing a total of 46 results. Urgh...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/435#issuecomment-170146709>
> .
>



-- 
Geoff Harder
Associate University Librarian
Information Resources and Digital Initiatives

University of Alberta Libraries
2-10H Cameron Library, University of Alberta
Edmonton, AB, Canada T6G 2J8
780.492.7914

*geoffrey.harder@ualberta.ca <geoffrey.harder@ualberta.ca>
library.ualberta.ca <http://library.ualberta.ca>*

**Comment by sfbetz** [comment]
Yes - but that 3600 was a decline from over 5600 (I think) prior to the migration.  Hopefully we see these numbers improve as we work through our suite of GScholar issues!

**Comment by johnhuck** [comment]
Excerpt from https://scholar.google.com/intl/us/scholar/inclusion.html#troubleshooting

1. "Keep in mind that changes that you make on your website will usually not be reflected in Google Scholar search results for some time. New papers are normally added several times a week; however, updates of papers that are already included usually take 6-9 months. Updates of papers on very large websites may take several years, because to update a site, we need to recrawl it - the time it takes to recrawl a large site is usually limited by the speed at which the target website is able to deliver content to the search robots."
3. "Failure to follow these guidelines could lead to exclusion of your content from Google Scholar."

Several aspects of the HydraNorth ERA do not conform to the GS guidelines. We've identified these aspects and are working on them, but in the meantime, the results that were crawled from the old ERA do indeed appear to be dropping out of the index.

**Comment by pgwillia** [comment]
<pgwillia> Does anyone know the Voodoo to get Google Scholar to index a Sufia app? ualbertalib is finding that we've lost our item count in Google Scholar since moving to Sufia.
<jcoyne> pgwillia: do you have a sitemap?
<pgwillia> uh... no. Is that the key?
<jcoyne> pgwillia: That's what PSU does: https://github.com/psu-stewardship/scholarsphere/blob/146522c609c2f22d5ea274f1c791edbc109a9055/lib/tasks/scholarsphere.rake#L366
<pgwillia> jcoyne++

**Comment by sfbetz** [comment]
We consider our current results list (over 9000) to be an indication that this ticket can be closed!
