### ISSUE TITLE
Dataverse object Deposit/modified time

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#450]
Currently the script it uses DateTime.now for both deposit and modified time as the information is not available in OAI-DC.  As the user to discover the objects in Hydranorth, I'd like to find the actual deposit and modified time of the object. 
- [x] check if the information available in other metadata source
- [x] modify the script to grab the information from appropriate source.

**Comment by johnhuck** [comment]
There are a number of dates in the DDI metadata that could be used. We would need to examine them and decide what should be mapped to 'deposit' and 'modified'. There may also be other dates in 'log'-oriented systems metadata, but I am only guessing.

One thing to take into account is that Dataverse allows users to create new versions of their studies, versions which are numbered, dated and tracked. Some of the dates in the metadata apply to the study and do not change when a new version is registered, and some dates apply to the version. A study version date may be a candidate for a 'modified' date, but this needs to be investigated.

I will add more information about dates in the DDI when I find my notes (which I think I left at home).

**Comment by pbinkley** [comment]
System dates in the OAI service (if any) could also be used. See #493. This issue should be resolved based on what works for automation, and therefore depends on #493, but John will advise on DDI's dates and preferences for metadata fields there.

**Comment by johnhuck** [comment]
production date
distribution date
deposit date
version date

XPath for these dates
/codeBook/docDscr[1]/citation[1]/distStmt[1]/distDate[1]
/codeBook/docDscr[1]/citation[1]/verStmt[1]/version[1]/@date
/codeBook/stdyDscr[1]/citation[1]/prodStmt[1]/prodDate[1]
/codeBook/stdyDscr[1]/citation[1]/distStmt[1]/depDate[1]
/codeBook/stdyDscr[1]/citation[1]/verStmt[1]/version[1]/@date

Distribution date is used in the citation. Production date is used in citation when no distr. date.

The dates to choose from in the DDI are :
-production date (when the data was created. it is mapped to dc:date in the oai_dc, which is blank if there is no production date).
-deposit date (when the data is uploaded to Dataverse, I presume. This date is different from distribution date because there is a two step process: after a study is created, it needs to be released before it is visible to the public.
-distribution date (the date which is used in the auto-generated citation, and which I assume is the date a study is released. There can be a lag between when a study is deposited and when the user chooses to release it).
-version date. (Dataverse registers a new version whenever a change is made to metadata or data objects). This is the closest thing to a date modified in the DDI metadata.

**Comment by pbinkley** [comment]
This should be coordinated with the decision about creation date in items migrated from ERA and with the OAI implementation.

**Comment by johnhuck** [comment]
@weiweishi or @pbinkley Could you give some more details about what the deposit and modified times are used for? With a better understanding I'll be able to make a better recommendation.

Are they mainly used for sort order of search results? Do they support other functions? Is the "Date (Newest first)" date for sorting order drawing from the 'deposit date' or the 'date created'? Thanks!

**Comment by johnhuck** [comment]
Based on the understanding that deposit/modified dates in ERA are system generated dates whose primary use is for ordering search results, I have identified a source for deposit/modified dates in the DDI record:

/codeBook/docDscr[1]/citation[1]/distStmt[1]/distDate[1]
/codeBook/docDscr[1]/citation[1]/verStmt[1]/version[1]/@date

That is, the 'distribution date' for date uploaded and 'version statement date' for date modified, but specifically the instances of these elements/attributes that occur in the docDscr element, not the ones in the stdyDscr element, for the reason that the former appear to be system generated, while the latter appear to be supplied by the user.

The first verStmnt element should be the most recent version, but for greater certainty we could match on the verStmnt element with the attribute @type="RELEASED"

The next question is what format is going to be most useful to your processes, @weiweishi. We get both DDI and DC records when we export metadata, but are you going to want to deal with two pieces of metadata to create or update each ERA object?

The obvious alternative is that I write a new stylesheet to generate our dcterms records from the DDI rather than the DC records, and ensure they include the new dates. dcterms:available and dcterms:modified would be likely candidates to carry the new dates. In the long run this is probably the better solution.

**Comment by sfarnel** [comment]
I think it would be great to have a larger discussion about this and
potential implications. If the date here is meant to allow for sorting on
new items in ERA then I would propose that the date an item was uploaded
into and/or modified in Dataverse would be somewhat misleading. Users are
directed back to Dataverse when they visit these items in ERA and can then
access the Dataverse specific data there. If we are looking at all other
items in ERA with regard to when they came into ERA (rather than another
separate system) then I think we should be consistent here in order to
avoid confusion.

On Tue, Feb 9, 2016 at 11:15 AM, johnhuck <notifications@github.com> wrote:

> Based on the understanding that deposit/modified dates in ERA are system
> generated dates whose primary use is for ordering search results, I have
> identified a source for deposit/modified dates in the DDI record:
>
> /codeBook/docDscr[1]/citation[1]/distStmt[1]/distDate[1]
> /codeBook/docDscr[1]/citation[1]/verStmt[1]/version[1]/@date
> <https://github.com/date>
>
> That is, the 'distribution date' for date uploaded and 'version statement
> date' for date modified, but specifically the instances of these
> elements/attributes that occur in the docDscr element, not the ones in the
> stdyDscr element, for the reason that the former appear to be system
> generated, while the latter appear to be supplied by the user.
>
> The first verStmnt element should be the most recent version, but for
> greater certainty we could match on the verStmnt element with the attribute
> @type <https://github.com/type>="RELEASED"
>
> The next question is what format is going to be most useful to your
> processes, @weiweishi <https://github.com/weiweishi>. We get both DDI and
> DC records when we export metadata, but are you going to want to deal with
> two pieces of metadata to create or update each ERA object?
>
> The obvious alternative is that I write a new stylesheet to generate our
> dcterms records from the DDI rather than the DC records, and ensure they
> include the new dates. dcterms:available and dcterms:modified would be
> likely candidates to carry the new dates. In the long run this is probably
> the better solution.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/450#issuecomment-181988935>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by pbinkley** [comment]
Since it sounds like it will be useful to get this thrashed out, I'll set
up a meeting.

Peter

Peter Binkley, Ph.D., MLIS
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by pbinkley** [comment]
At our date summit today it was decided that John would examine the DC delivered by Dataverse after an item is changed on the Dataverse side, to determine what date information could usefully be updated on the ERA side.

**Comment by johnhuck** [comment]
On Friday I said I would answer the question of how the Dataverse's oai_dc identifies the version of a study (A new, numbered version is published every time the study metadata or files are updated).

The only place the version number is mentioned that I can see is in the formatted citation (one of the dc:description elements). There is, of course, no release date for a version in the oai_dc.

So, our current export/transformation/ingest workflow for Dataverse metadata is not capturing the study version, although it could.

I have also gone back and taken a look at more of DDI metadata examples and I need to correct something i said earlier in this thread:

The value for /codeBook/docDscr[1]/citation[1]/distStmt[1]/distDate[1] is *not* date uploaded, as I said, but rather is usually the release date of the most recent version. However, this is not consistent. Sometimes it is a date later than the date of the most recent version and sometimes it is an earlier date, with no obvious explanation.

Given that it is inconsistent, I think it would be better to take the release date of version 1 as equivalent to a date of original deposit or upload and the release date of the most recent version as a 'date modified' date. All other date values appear to be user generated.

To be entirely honest, I was unclear on Friday what the consensus decision was going forward: I believe that we agreed that date_uploaded and date_modified would refer to the upload and modify dates pertaining to an original system for migrated resources, which would suggest using the version dates from Dataverse as I've described.

But I also remember @sfbetz saying that the important thing was the user be able to distinguish items new to the ERA interface, and also the suggestion (I forget who said it) that, as metadata-only objects, Dataverse metadata in ERA is not on the same level, leading me to wonder if we had agreed not to consider the dataverse dates and just work with timestamps from Fedora.

If I were to guess, I think we decided on the former, not the latter, but perhaps someone could clarify for me, thanks.

**Comment by johnhuck** [comment]
After speaking with @sfarnel and @pbinkley, I have the understanding that the consensus is that we will attempt to capture the version dates from Dataverse for use as date uploaded and date modified in ERA, and so will prepare a new stylesheet to make dcterms metadata from the DDI.

**Comment by johnhuck** [comment]
Work on the stylesheet is essentially complete. Corrections and refinements will be completed after running it with the next set of exported data.
