### ISSUE TITLE
Handle Dataverse related collections and community

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#452]
Dataverse structure:
Dataverse Network -> dataverses -> studies

In currently migration script, all studies are migrated as objects, and put into a "Dataverse Datasets" collection. Stakeholders' inputs are needed to advise how to organize the migrated objects. Should we map the Dataverse structure to something like: Dataverse Community -> Multiple Dataverse Collections -> individual studies?

**Comment by pbinkley** [comment]
Note that membership in a Dataverse (equivalent of a HydraNorth collection) is not in the DDI metadata; it's not clear how we could retrieve it.
Question for stakeholders: is this necessary for discovery in HydraNorth?

**Comment by wyman10** [comment]
Just for clarity what do you mean by membership in a dataverse? Does it mean that a user can see the individual studies (as objects) in the Hydra North "Dataverse Datasets" collection as a result of a search but not their relationship with other studies in the same dataverse or DV collection?

**Comment by johnhuck** [comment]
@wyman10, yes that is correct. The name of the Dataverse (e.g., "Thomas Melville Hess Collection") that a study belongs to is included in neither the DDI metadata nor the OAI_DC. We would need to investigate to see whether that information could be extracted from Dataverse another way.

One more detail to add: apparently you can create collections within a Dataverse to organize studies in that Dataverse, but that information is also not present in the DDI or OAI_DC. Here is an example of a Dataverse with collections:
https://dataverse.library.ualberta.ca/dvn/dv/HessCollection

**Comment by wyman10** [comment]
It is one of the fields that is populated automatically in DV and I just checked, and you can not even see it when you are editing/creating the metadata in DV. So essentially if a user wants to see all of the related studies in a dataverse they will have to access that via the "Original Dataverse" field in DV (after they have selected a particular study in Hydra North that points them back via the DOI to dataverse.

It would be nice to discover the name of the dataverse in Hydra North but if it is not there in DDI or OAI_DC then we can not make use of it at this time.

**Comment by chumphre** [comment]
DDI does have some elements that could be used to capture the descriptive
information for the Dataverse title under which it was organized. For
example, under <stdyDscr> are a set of elements for production,
distribution, and series identification. Dataverse does report the
production and distribution elements in its exported DDI file. Larry and I
found that series identification is a field that can be added to a study by
editing the study metadata. But the Dataverse name isn't an intended use
for a series description (a series represents the name of a recurring data
collection, such as, the monthly Canadian Labour Force Survey). There is a
<notes> element is <stdyDscr> that could be used to include the Dataverse
information. The problem is how to implement this when Dataverse itself
doesn't produce this element in its exported DDI file. One would have to
write a script to patch in the <notes> element with Dataverse information
after the DDI metadata have been exported.

**Comment by weiweishi** [comment]
Currently solved with a generic Dataverse community/collection. Maybe we can review with the new Dataverse version to see if the collection information is captured in the metadata.
