### ISSUE TITLE
KW search assumes OR between words

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#512]
As a user I want all simple search boxes to behave like the tools I'm most familiar with (Google) so that I can find items easily.

Searchbox in Hydra looking for any terms instead of all terms - users expect increased specificity with additional keywords but opposite is happening. 

Most users were still able to find content they were searching for using facets.

**Comment by pgwillia** [comment]
The assumption in the title about KW being 'OR'ed isn't exactly true.  For example a search for 'oil sands' is translated to the query 
```+(((contributor_tesim:oil | date_modified_tesim:oil | format_tesim:oil | date_created_tesim:oil | subject_tesim:oil | noid_tsi:oil | license_tesim:oil | all_text_timv:oil | date_uploaded_tesim:oil | ser_tesim:oil | file_format_tesim:oil | language_tesim:oil | trid_tesim:oil | title_tesim:oil | publisher_tesim:oil | description_tesim:oil | creator_tesim:oil | temporal_tesim:oil | resource_type_tesim:oil | spatial_tesim:oil | fedora3uuid_tesim:oil)~0.01 (contributor_tesim:sand | date_modified_tesim:sand | format_tesim:sand | date_created_tesim:sand | subject_tesim:sand | noid_tsi:sands | license_tesim:sand | all_text_timv:sands | date_uploaded_tesim:sand | ser_tesim:sand | file_format_tesim:sand | language_tesim:sand | trid_tesim:sand | title_tesim:sand | publisher_tesim:sand | description_tesim:sand | creator_tesim:sand | temporal_tesim:sand | resource_type_tesim:sand | spatial_tesim:sand | fedora3uuid_tesim:sand)~0.01)~2) (title_tesim:"oil sand"~2)~0.01```

While the terms are considered separately against a number of fields (contributor, date_modified, format, date_created, subject, noid, license, all_text, date_uploaded, ser, file_format, language, trid, title, publisher, description, creator, temporal, resource_type, spatial and fedora3uuid), proximity of terms and exact match as a phrase is also weighted.

[Minimum "Should" Match](http://lucene.apache.org/solr/4_10_3/solr-core/org/apache/solr/util/doc-files/min-should-match.html) specifies a minimum number of clauses that must match in a query. We have this set as ```2<-1 5<-2 6<90%``` which means that if there are 1 or 2 clauses one of the clauses is mandatory, if there are 3, 4 or 5 clauses two of the clauses are mandatory and if there are six or more clauses 90% are required. We can change these values.

Also, @redlibrarian might have some suggestions from the discovery results tweaking.

**Comment by redlibrarian** [comment]
Yes, we've been through this quite a bit. I've been trying to get the testing team out of the habit of thinking in terms of boolean logic when thinking about search behaviour, but in the end we've settled on "ANDish" and "ORish" to talk about this stuff, recognizing that this isn't a binary opposition, but a continuum.

That said, I made our search 100% "ORish" by setting the mm field to (I think) 0, which basically made every record match on every query, because this seemed to fix a different problem (which I'll get back to). In the end I restored the Blacklight default mm value to what HydraNorth currently has (2<-1 5<-2 6<90%) and this has been working to the satisfaction of the Blacklight testing team. It's strange that with the same mm value you're seeing too many search results. Some example searches might be a good idea to collect.

Just a note on the problem I was trying to fix when I changed the mm. With the default setting, some field-types need to be adjusted from "string" to "text" or vice-versa in order to allow for e.g. proper whitespace breaking in combining search terms, proper stopword functionality. Moving mm in a more "ORish" direction fixed the problem, but at the cost of imprecise search results. Resetting the default mm meant I had to look for another solution which was to adjust the field type where necessary (this may not be an issue for Hydra if you aren't modifying the search indexes or if you are not using a lot of dynamic fields, as we are). Hope this helps. Let me know if I can expand/clarify anything.

**Comment by redlibrarian** [comment]
@sfbetz Do you have an example search that you've found problematic?

**Comment by sfbetz** [comment]
After hearing lots about @redlibrarian 's work on this, I now understand this is way more complex than and / or! Also, after chatting with Peter, I think that some of the seeming lack of specificity may have to do with fields we're not indexing instead of how Blacklight is working. Finally, there's some pretty sketchy metadata in ERA that will impact discovery.

This particular issue came from user testing - we had participants do a simple search task: "find articles that your colleague Ian Stirling has written about polar bears." One sample search I remember was: stirling polar bears - pulls up 64 results - the first two results look good; 3,4,5 look unrelated, 6 looks good, and following results on that page look irrelevant. I'd want to see some increased specificity here I think.

https://era.library.ualberta.ca/catalog?utf8=%E2%9C%93&q=stirling+polar+bears

**Comment by redlibrarian** [comment]
@sfbetz @pgwillia @pbinkley There were **a lot** of fields missing from default Blacklight that the Discovery Testing team wanted to see, and adding these necessitated playing with weights as well as tweaking the field types, but eventually we got to a place where the testers are generally happy with the search results. @sfbetz It's interesting that you should say that results 3, 4, 5 look unrelated, as they all have the phrase "polar bears" in their subject field. If this is in fact the case, then subject can be weighted lower in the index to address it, but I wouldn't want to do that before investigating whether that's more of a data problem (i.e. should those items have "polar bears" as subject terms). A lot of these newer systems expose issues in your metadata. :)

**Comment by redlibrarian** [comment]
@sfbetz @pgwillia @pbinkley This is a document I prepared for staff to understand how indexing/searching is different in Blacklight than other library search tools. It's pretty high level (perhaps so high level as to be inaccurate in places), but it might be useful: https://docs.google.com/document/d/1F7CUwSw-7T5KtwrXxNMOyOFtwzVGdhGV_Ry9lHh7_4k/edit?usp=sharing

**Comment by sfbetz** [comment]
Thanks @redlibrarian! I will look at this. I think it's not that those results were unrelated conceptually, but for the user, who was primarily interested in their colleague Stirling's articles, then they were not useful - they wanted to see articles by Stirling about polar bears. I think in an IR, the issue of authorship is probably more important than subject, especially when we have such inconsistent (read bad) metadata in the subject field (self-deposit FTW).

**Comment by redlibrarian** [comment]
@sfbetz Ah, now I see - for sure. Part of that is going to be down to metadata, but also to the KW nature of the Blacklight search. I had removed the Author facet from Blacklight, but put it back in at the request of the team, and also added a "more by this author" link in the records themselves (both of which ERA already has). For users who don't want to "search broadly then facet", I think the advanced search is a better bet (which ERA has on the "Search" page). Searching there for "stirling, i" brings up 3 results, all of which have Ian as author/creator (though interestingly, the result list only displays the first creator, which might make the third result look like a false positive.

**Comment by pgwillia** [comment]
@sfbetz not sure how you want to approach this. We could optimize the query parameters (perhaps by boosting creator/contributor?) to get the best results for the "stirling polar bear" query at the risk of de-optimizing other queries.

Do you have a sense of which fields you think are not being indexed?

Thinking out loud... it might be useful to create a 'query calibration' tool? We could use it as part of user testing. How it might work is to take real queries from the logs and present the user with two panes.  In the left pane would be the original query with the original results, in the right pane the user would be given an interface like a soundboard/mixing console where as they change the query inputs using unlabelled sliders the changes to results are reflected in the pane.  When the user feels that they have the best results set for the query they would 'save' it. We would then look at patterns in the saved query inputs to tune our searches.

**Comment by redlibrarian** [comment]
@pgwillia Just one more comment, re: the query calibration tool. Stanford did some work with getting users (in their case, library staff) to help write Cucumber tests against a fairly comprehensive (and known) test set. The tests looked at number of results ("I expect x results to be returned") and relevance ("I expect results x and y to be in the top two slots"). I wanted to do this with Blacklight but we've run out of time - I like your approach too, and I wonder if the saved search could be converted into a test so that you could tell if down the road an indexing tweak broke that search. One other thing to bear in mind is that you may end up with contradictory expectations, so you'd need a way to compromise or choose one or the other...

**Comment by pbinkley** [comment]
I think the non-indexed fields are dissertant and abstract, which need to
be indexed into creator and description as in #837 .

Peter Binkley, Ph.D., MLIS
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243
