### ISSUE TITLE
Add 'Abstract' to metadata display

### ISSUE THREAD

**Issue by johnhuck** [ualbertalib/HydraNorth#547]

**Comment by johnhuck** [comment]
I am considering changing the Dataverse => Hydra mapping, so that content in the "abstract" field is put into a description field instead. I originally chose "abstract" to conform to the DDI element "abstract." However, I have subsequently learned that the Dataverse schema, in fact, uses "description" as the label for the field and maps it to DDI "abstract" when DDI metadata is exported.

If I follow through with this change, this issue will be a very low priority. However, if I leave the mapping as is, the priority will be high.

**Comment by weiweishi** [comment]
Since dataverse objects shares the same model as generic objects, with same
fields. It will be minimal development work required if the mapping can be
changed.

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by johnhuck** [comment]
This task is no longer required. The mapping from Dataverse to ERA puts the textual description in dcterms:description, not dcterms:abstract.
