### ISSUE TITLE
add links to previous versions of Creative Commons' licenses. 

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#561]
Migrated objects will often have CC licenses in version 3.0. External links need to be added to these license on CC's website. 

Licenses to be included are:
Creative Commons Attribution 3.0 Unported
Creative Commons Attribution-Non-Commercial 3.0 Unported
Creative Commons Attribution-Non-Commercial-No Derivatives 3.0 Unported
Creative Commons Zero Waiver

Example:
http://plano.library.ualberta.ca/files/bv73kq926#.VdyjSxRVhBd

**Comment by mbarnett** [comment]
I've added a mapping between these Licenses and the URLs on the Creative Commons website. Should users be able to select these licenses for new objects or when editing existing objects? (I'm guessing no, and went ahead with the fix under that assumption, but it's an easy change if we do want to make them available).

I think this uncovers a couple of other bugs in the license metadata, though. Existing migrated objects appear to store the name of the license in the "license" field in Fedora. *Newly created* or *edited* objects in the new interface, however, store the URL of the license in that field. 

The records/show_fields/_license partial *looks like* it was written with the assumption that the license *name* would be stored in the record (although there's a bug in it that's preventing it from working properly, if that's what it's meant to be doing), instead of the URL, whereas the edit_fields partial seems to make the opposite assumption. We'll need to decide which way is correct and fix both partials to ensure consistency with the migration in order to move forward with this fix.

**Comment by pbinkley** [comment]
You're right that the old versions of licenses should not be available for users to apply to new items.
We'll need @sfarnel  to speak to whether the license field ought to contain the name or the url.

**Comment by sfarnel** [comment]
We've mapped this to contain the url. when we move into phase 1 linked
data, where we sort out the string vs. uri question, we can see if we are
able to store uri (i.e., url in this case) but display a string.

The nice thing is that the CC urls are pretty obvious to the user.

On Fri, Aug 28, 2015 at 4:59 PM, Peter Binkley <notifications@github.com>
wrote:

> You're right that the old versions of licenses should not be available for
> users to apply to new items.
> We'll need @sfarnel <https://github.com/sfarnel> to speak to whether the
> license field ought to contain the name or the url.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/561#issuecomment-135906995>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685
