### ISSUE TITLE
NOIDs are registered as ARKs with EZID

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#571]
Background: https://docs.google.com/document/d/1SiveohuDF6iZQI6Pe-3pWEOyJfoN5tFtLxoSqIXSOXQ/edit#heading=h.17bfp33yiyr5

Metadata: EZID will look for Datacite record (as used for DOIs), but will accept simpler record (minimum: author, title, date) - we will need to handle some items without dates.

Question: how easily can we update the metadata later?

**Comment by sfarnel** [comment]
EZID documentation for registering ARKs and DOIs can be found at http://ezid.cdlib.org/doc/apidoc.html

Minimum required metadata for ARKs: title (erc.what), creator (erc.who), date (erc.when)
Minimum for DOI: title (dc:title), creator (dc:creator), publisher (dc.publisher), date (dc.date) (which map to corresponding erc elements above)

Additional metadata is encouraged; we can provide other metadata we have.

Note: in ERA (i.e., the institutional repository part of Hydra North) we currently have publisher only from datasets via Dataverse. For items will need to determine value of publisher (e.g., University of Alberta Libraries?)
Note: post-launch we will be tackling the issue of items with no date (which will actually be relatively few in number once we tackle known issues). EZID provides options for cases where a meaningful value for a required element is not available; see http://ezid.cdlib.org/doc/apidoc.html#metadata-requirements-mapping

**Comment by johnhuck** [comment]
After reviewing the EZID documentation, and with @sfarnel's agreement, I am recommending that we supply metadata in DataCite format for ARKs. Full details are in the linked document.

If we accept this recommendation, here are some next-step tasks we will need to consider:

* Should we supply metadata in individual profile elements in ANVL format (e.g., 'datacite.creator : Author, Name') or in an appended XML document?
* We know we need 'date' for a number of purposes, and it is highly recommended for ARK registration, but not required. Should we undertake work now to remediate as many ERA records that lack date as we can before we begin registering ARKs, or later and then update records?
* We know we will need 'publisher', which most ERA items lack, if we wish to register DOIs in the future. Should we wish to make a decision now regarding what value to provide for this element, so that it can be included in the datacite metadata we register for the ARKs? 
* If we follow the recommendation and supply datacite.resourcetype, we will need to create a mapping from ERA types to the datacite types.
* a new sheet in the HydraNorth Data Dictionary will show mappings between ERA metadata and DataCite elements.

There may be some other things to think about that will come to mind later. 

https://docs.google.com/document/d/1xVFUbVOpdrIOs-Jv1I0CMmbajcHlUXfN0Grc5CY4tJo/edit?usp=sharing

**Comment by sfarnel** [comment]
Parsing out dates is valuable/necessary for many things, including DOIs,
ARKs, more sophisticated sorting/browsing and OAI, and more. I think this
is an issue worth tackling sooner rather than later before our focus shifts
to other content.

On Mon, Nov 23, 2015 at 5:03 PM, johnhuck <notifications@github.com> wrote:

> After reviewing the EZID documentation, and with @sfarnel
> <https://github.com/sfarnel>'s agreement, I am recommending that we
> supply metadata in DataCite format for ARKs. Full details are in the linked
> document.
>
> If we accept this recommendation, here are some next-step tasks we will
> need to consider:
>
>    - Should we supply metadata in individual profile elements in ANVL
>    format (e.g., 'datacite.creator : Author, Name') or in an appended XML
>    document?
>    - We know we need 'date' for a number of purposes, and it is highly
>    recommended for ARK registration, but not required. Should we undertake
>    work now to remediate as many ERA records that lack date as we can before
>    we begin registering ARKs, or later and then update records?
>    - We know we will need 'publisher', which most ERA items lack, if we
>    wish to register DOIs in the future. Should we wish to make a decision now
>    regarding what value to provide for this element, so that it can be
>    included in the datacite metadata we register for the ARKs?
>    - If we follow the recommendation and supply datacite.resourcetype, we
>    will need to create a mapping from ERA types to the datacite types.
>    - a new sheet in the HydraNorth Data Dictionary will show mappings
>    between ERA metadata and DataCite elements.
>
> There may be some other things to think about that will come to mind
> later.
>
>
> https://docs.google.com/document/d/1xVFUbVOpdrIOs-Jv1I0CMmbajcHlUXfN0Grc5CY4tJo/edit?usp=sharing
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/571#issuecomment-159109206>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by johnhuck** [comment]
I have added information about the numbers of ERA items lacking dates to the Google Doc linked from my previous post. In summary, the format required for datacite.publicationYear is YYYY (there is another datacite element for more specific dates, ranges, of different types).

Many items that have a dateCreated value will need to be processed to extract a year (yyyy). Almost all theses have a value in date_accepted (80 don't), which takes care of a lot of blank date values. Here is a breakdown of the numbers. Again, see the document linked above for more details.

Items with YYYY date (date can be used as-is): 5,197
Items with non-YYYY date (extract YYYY from date_created_ssi): 10,880
Theses without date, with date_accepted value (extract YYYY from date_accepted): 18,160
Journal articles without date (alternate processing required): 1,571
Images without date (alternate processing required): 482
Other items without date (alternate processing required): 571
Items without date with item type 'null' or '(blank)': 136

**Comment by sfarnel** [comment]
Thanks John.

I think we need to further investigate the last four categories to
determine processing needed. Some may have dates embedded in the metadata
that can be extracted, others may not have any obvious date in which case
we have to look at options that are meaningful and reasonable.

On a related note we need to know more about the 136 items with item type
null or blank; these are suspicious. (Unless the data extract included
communities and collections, for example, in which case it would make more
sense).


On Tue, Nov 24, 2015 at 5:36 PM, johnhuck <notifications@github.com> wrote:

> I have added information about the numbers of ERA items lacking dates to
> the Google Doc linked from my previous post. In summary, the format
> required for datacite.publicationYear is YYYY (there is another datacite
> element for more specific dates, ranges, of different types).
>
> Many items that have a dateCreated value will need to be processed to
> extract a year (yyyy). Almost all theses have a value in date_accepted (80
> don't), which takes care of a lot of blank date values. Here is a breakdown
> of the numbers. Again, see the document linked above for more details.
>
> Items with YYYY date (date can be used as-is): 5,197
> Items with non-YYYY date (extract YYYY from date_created_ssi): 10,880
> Theses without date, with date_accepted value (extract YYYY from
> date_accepted): 18,160
> Journal articles without date (alternate processing required): 1,571
> Images without date (alternate processing required): 482
> Other items without date (alternate processing required): 571
> Items without date with item type 'null' or '(blank)': 136
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/571#issuecomment-159448472>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by johnhuck** [comment]
Thanks, Sharon. Yes, this gives us a general picture of how many items would require some kind of work for us to be able to submit a date in the required format. And the last four are the ones we will want to examine more closely to decide whether to include them in the present work or register them for ARKs first. 

The second and third categories will also require work. Given that they represent the vast majority of ERA content, It seems to me that we should try to get dates in the correct form for these categories before registering ARKs for them, unless there is a compelling reason not to (see below).

The question comes to mind: will we be able to automate the extraction of a YYYY date for these categories, so that it can be done on the fly at the moment of the API request, or will it require a degree of manual intervention or supervision?

If manual intervention is necessary (or even if it isn't), should we consider a way to capture the derived YYYY date in our metadata so that we only need to perform the derivation once (and so we don't have to maintain a stylesheet or script). This path leads to issues more complex than we perhaps want to consider at the moment (adding a new element to our data dictionary?), but it seems to me that the only quick solution in this situation is to fall back on using the unassigned/unavailable codes if we want to minimize the extraction/normalization work. Some normalization work on dates is, I think, unavoidable, regardless of the metadata profile we choose: ISO 8601 is recommended for dc.date and TEMPER is expected for erc.when. On our end, to cite a few examples, the date_accepted dates include time stamp information, we have to screen for date ranges, and most dates are not in ISO syntax.

Submitting a YYYY date at least leaves control of choosing the publication year in our hands, rather than giving it over to EZID normalization scripts that we don't have access to (if, in fact, there are scripts that take whatever date information might be in a dc.date or erc.when element and produce a year value for the citation).

We will definitely need to use the (:unas) unassigned or (:unav) unavailable codes for some categories, and the question is which ones. We may wish to buy ourself time to come up with a proper long-term solution.

**Comment by sfarnel** [comment]
Thanks John.

I agree that all of these need investigation.

We will need to work with the dev team to understand whether this is
something that should be generated once and stored as a new property solely
for this purpose or should be generated on the fly.

We intentionally did not require ISO format for dates fro a variety of
reasons, instead choosing to go with EDTF because of added flexibility. We
wil certainly need that flexibility when we start to incorporate other
materials as well.

Having said that, again, we can in most cases generate a yyyy date for
these purposes only while leaving the original semantic intent of date
intact.

For theses, yes, dateAccepted should be the date privileged, with necessary
capture in ISO format for registration purposes only.

Some items do not have date as a separate property, but it may be found in
another property, which we can extract. Others will not have a date at all
and in those cases for at least the short term we can use :unas or :unav;
considering some sort of review and assignment of dates is something to
consider long term and which has implications.

Once we know how many have some type of EDTF date/time expression that
isn't obviously reducible to yyyy we can assess and address either with
:unas or :unav or generation of a yyyy as a separate property, with the aim
to leaving the original semantic meaning intact.

Cheers,
Sharon

On Wed, Nov 25, 2015 at 11:28 AM, johnhuck <notifications@github.com> wrote:

> Thanks, Sharon. Yes, this gives us a general picture of how many items
> would require some kind of work for us to be able to submit a date in the
> required format. And the last four are the ones we will want to examine
> more closely to decide whether to include them in the present work or
> register them for ARKs first.
>
> The second and third categories will also require work. Given that they
> represent the vast majority of ERA content, It seems to me that we should
> try to get dates in the correct form for these categories before
> registering ARKs for them, unless there is a compelling reason not to (see
> below).
>
> The question comes to mind: will we be able to automate the extraction of
> a YYYY date for these categories, so that it can be done on the fly at the
> moment of the API request, or will it require a degree of manual
> intervention or supervision?
>
> If manual intervention is necessary (or even if it isn't), should we
> consider a way to capture the derived YYYY date in our metadata so that we
> only need to perform the derivation once (and so we don't have to maintain
> a stylesheet or script). This path leads to issues more complex than we
> perhaps want to consider at the moment (adding a new element to our data
> dictionary?), but it seems to me that the only quick solution in this
> situation is to fall back on using the unassigned/unavailable codes if we
> want to minimize the extraction/normalization work. Some normalization work
> on dates is, I think, unavoidable, regardless of the metadata profile we
> choose: ISO 8601 is recommended for dc.date and TEMPER is expected for
> erc.when. On our end, to cite a few examples, the date_accepted dates
> include time stamp information, we have to screen for date ranges, and most
> dates are not in ISO syntax.
>
> Submitting a YYYY date at least leaves control of choosing the publication
> year in our hands, rather than giving it over to EZID normalization scripts
> that we don't have access to (if, in fact, there are scripts that take
> whatever date information might be in a dc.date or erc.when element and
> produce a year value for the citation).
>
> We will definitely need to use the (:unas) unassigned or (:unav)
> unavailable codes for some categories, and the question is which ones. We
> may wish to buy ourself time to come up with a proper long-term solution.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/571#issuecomment-159694708>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by pbinkley** [comment]
Summary of our discussion after standup today
- metadata team will come up with scenarios for date values they want to be able to cover that would not be handled properly by the four-digit-regex extraction method (based on the date facet extract)
- our general strategy is to provide an "unassigned" value programmatically during export where the date field isn't populated, so that we can export valid metadata without having first to change every item that doesn't currently have a date
- metadata team will also consider what other labels they might want to track
- based on these requirements, we'll decide whether putting labels in the current date field is sufficient, or whether another admin-only field is needed
- at a later stage we'll look at extracting dates from the citation field using a four-digit regex; we'll export a csv file with noid, citation, and extracted date, for review by the metadata team and (if all goes well) for subsequent re-import to populate the date field with the extracted date.

**Comment by johnhuck** [comment]
Thanks, @pbinkley. Actually, my take-away from our chat today is that I think we would like to look at extracting dates from alternate fields now rather than later. I am working to prepare a list of NOIDS for you to extract more complete metadata for. (Faceting in open refine takes a long time on a big record set like this.) After reviewing what you send me, we are hoping to be able to identify a set of items that will be easy to extract a date from and another set that won't that we won't attempt to tackle now.

I have also reviewed the date formats in the dcterms:created and dcterms:date_accepted elements, and can say that a regex expression looking for a 4 digit number somewhere in the value will work in the vast majority of cases. I will give more details shortly, but that's the bottom line.

**Comment by sfarnel** [comment]
Thanks both. I concur with @johnhuck in that looking at extracting was
'later' in the sense that the dcterms:created and dcterms:date_accepted
would be reviewed first, which it looks like is close to being ready to go.

On Thu, Nov 26, 2015 at 2:19 PM, johnhuck <notifications@github.com> wrote:

> Thanks, @pbinkley <https://github.com/pbinkley>. Actually, my take-away
> from our chat today is that I think we would like to look at extracting
> dates from alternate fields now rather than later. I am working to prepare
> a list of NOIDS for you to extract more complete metadata for. (Faceting in
> open refine takes a long time on a big record set like this.) After
> reviewing what you send me, we are hoping to be able to identify a set of
> items that will be easy to extract a date from and another set that won't
> that we won't attempt to tackle now.
>
> I have also reviewed the date formats in the dcterms:created and
> dcterms:date_accepted elements, and can say that a regex expression looking
> for a 4 digit number somewhere in the value will work in the vast majority
> of cases. I will give more details shortly, but that's the bottom line.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/571#issuecomment-159995204>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by johnhuck** [comment]
Here is the list of NOIDS that have a blank dcterms:created value, and that are not theses.

[blank_date_created_NOIDS.txt](https://github.com/ualbertalib/HydraNorth/files/45287/blank_date_created_NOIDS.txt)

@pbinkley, Could you provide a report for these NOIDS, please, that adds these fields to the query you used previously? Thanks!
dcterms:relation
dcterms:isVersionOf
dcterms:source

**Comment by johnhuck** [comment]
Here are more details about the types of 'problematic' values in dcterms:created that a regex expression will have trouble with. The full list is at the bottom, and I've categorized the types 

At this time, the simplest thing might be to have us review these cases and choose the date. Later maybe we could codify rules, once we have a sense of things. For instance, whether to choose the earlier or later year might depend on whether it's a resource that was created over a span of time (later date is germane) or a serial publication (earlier date is germane).

Types of 'problematic' values:

Multiple dates together
1980, 1981, 1994

Pairs of dates and closed date ranges
1943/1944
1966-2011
2004/11/19-2004/11/21

Open date ranges
1979-

Probable dates
198-?

Typos (ostensible)
19691969
2-15/06/03

Textual values
Attribution-NonCommercial 4.0 International
test

Full list of values found:
1943/1944
1966-1970
1966-2011
1968/1969
1969-1988
19691969
1970-1985
1974/1975
1979-
1979-1982
198-?
1984-1995
1995-2011
1980, 1981, 1994
2-15/06/03
2004/11/19-2004/11/21
Attribution-NonCommercial 4.0 International
test

**Comment by johnhuck** [comment]
@pbinkley, I think that all the information you should need to recreate the query for the NOIDS is in my comment above that includes the NOID list text file. If not, let me know.

**Comment by johnhuck** [comment]
I have completed metadata field mapping with processing instructions and have reviewed them with @sfarnel. They are contained on a new sheet in the HydraNorth Data Dictionary.

https://docs.google.com/spreadsheets/d/1hSd6kf4ABm-m8VtYNyqfJGtiZG7bLJQ3fWRbF_nVoIw/edit#gid=1902267812

I am still looking at the set of items without dates and hope to have a recommendation about whether to try to parse a YYYY date from the formatted citation within the next day or two.

**Comment by johnhuck** [comment]
Hello @weiweishi @pbinkley and @criedlberger,

I have completed a preliminary review of the 1,000 or so remaining "date-less" ERA items and have concluded that, while there are perhaps a hundred or two hundred or perhaps more items that have a promising year value in a file name, rights statement, title or other field, there isn't another sizeable set of "low-hanging fruit" that would be easy to act on immediately. The potential year values are scattered over a number of fields and we will have to take time to verify each case.

So, @sfarnel and I agree that you should proceed with registering ARKs with the metadata that we currently have according to the instructions that I have laid out in the "EZID (ARKs)" sheet of the HydraNorth Data Dictionary:

https://docs.google.com/spreadsheets/d/1hSd6kf4ABm-m8VtYNyqfJGtiZG7bLJQ3fWRbF_nVoIw/edit#gid=1902267812

A few details in those instructions I'd like to draw to your attention:

1. We want to include 4 DataCite elements. The ERA metadata fields that map to these DataCite elements are different, depending on whether the item is a thesis or not.
2. Use the code '(:unav)' [parentheses are part of the code] as the value for 'datacite.publicationyear' whenever a YYYY value can't be extracted from the specified fedora metadata fields.
3. There is a set of items that have multiple date values in the date_created field, that have an open date range value ("1979-"), or that otherwise do not have a value that will resolve to a single YYYY value. I've documented these cases on the GitHub issue thread above. Please either have me review these cases or use the '(:unav)' code until we can verify the correct YYYY value for these items. I think there may be less than 50 of these cases.
4. Use the mapping from ERA types to DataCite types found on the same sheet for all 'datacite.resourcetype' values. Use the 'general/specific' pairs (e.g., 'Text/Book').

Any questions, feel free to shoot them my way. Thanks!

**Comment by pbinkley** [comment]
Closed by #973
