### ISSUE TITLE
migrated item missing subjects (there may be others?)

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/HydraNorth#666]
https://hydranorth.library.ualberta.ca/files/8049g504g#.VhKIN0ZSn9V

in old ERA: https://era.library.ualberta.ca/public/view/item/uuid:d3cba59b-cd26-48d2-a497-74784f791b4c/
metadata is in transformed foxml

**Comment by pbinkley** [comment]
My first thought was that this was due to a glitch in the fix to multivalue term imports which I made on Friday, but other items imported in the same block have their subject headings (e.g. https://hydranorth.library.ualberta.ca/files/2801pg51k#.VhKWy5cy3mE = http://hdl.handle.net/10402/era.25264 ). We'll need to check the logs.

**Comment by pbinkley** [comment]
The log entry for the migration of this item (noid 8049g504g) shows that it was migrated from a different uuid:

```[INFO  2015-10-02 13:08:38] COMPLETED uuid:00abdd9f-397b-4e0c-9009-771c8130d1ba from era_final_migration/00//uuid_00abdd9f-397b-4e0c-9009-771c8130d1ba.xml as 8049g504g in collections ["uuid:dc9e6777-b6ec-47a9-8455-14da2fc3fd2a"] and communities ["uuid:e62852dc-71cd-492d-9f5e-f25fe6bbc769"]```

https://era.library.ualberta.ca/public/view/item/uuid:00abdd9f-397b-4e0c-9009-771c8130d1ba/ appears to be a different version of the same item, but without subjects. So it appears that the problem is duplication in old ERA rather than a glitch in the migration.

**Comment by sfarnel** [comment]
Ah, interesting. I see though that https://era.library.ualberta.ca/public/view/item/uuid:00abdd9f-397b-4e0c-9009-771c8130d1ba/ is an initial (inactive) version of the public item. (I've now deleted it) I believe the migration script catches duplicates by UUID; catching others is trickier. We may run into a few more of these. I'm hoping a full reconciliation post-migration will help us clean out all of these items once and for all.

**Comment by pbinkley** [comment]
Yes, the script only looks for duplicate uuids. When we're done we should discuss what kind of report would help discover these cases.

**Comment by sfarnel** [comment]
similar issue with a number of items that have only title metadata and are findable by browsing by language (including typo!) 'no liguistic content': https://hydranorth.library.ualberta.ca/catalog?f[language_sim][]=No+liguistic+content&page=15&q=

**Comment by sfarnel** [comment]
Will be addressed in #715 
Closing
