### ISSUE TITLE
Collection size

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#692]
Our use style of collections in ERA is clearly overwhelming our Sufia-based model. I think we need to be able to render a collection with a Solr query to a collection facet rather than our current model of addressing all members. We made changes to support large collections in #201 but clearly not enough.

**Comment by pgwillia** [comment]
Might be because the presenter queries fedora for each member of a collection to find permissions... which in the case of the "Northern North America Collection" is 1132 times.

    model.members.select do |item|
      render_context.can? :read, item
    end.count
[https://github.com/ualbertalib/HydraNorth/blob/master/app/presenters/hydranorth/collection_presenter.rb#L38-L40]

Quickest fix is to remove the count, or see if the value used in pagination is useful.

**Comment by pbinkley** [comment]
Could we replace it with a solr query that searches for members of the
collection and returns a permissions facet with item counts? We could then
have logic to report a number to the user based on the user's permissions
to view different items.

**Comment by pgwillia** [comment]
That's along the lines that I was thinking.  The query that is built to get the collection members already accounts for permissions. Using the numDocs from that or the value that used to calcuate pagination should accomplish this.  Just trying to figure out how to access either of those values from the presenter.

**Comment by pgwillia** [comment]
I can see the value that I want in the render_context object (from [collection_presenter](https://github.com/ualbertalib/HydraNorth/blob/master/app/presenters/hydranorth/collection_presenter.rb)) but can't figure out the hash foo to isolate it.

```
...
"response"=>{
  ...
  "response"=>{
    "*numFound*"=>0,
    ...
  }
}
...
```
