### ISSUE TITLE
review current minter-state on cluster

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#696]
During the attempted service launch, we discovered that the production server was unable to create new Batch/GenericFile/Collection, whenever it needs to mint a new ID. Further investigation discovered that the minter state file need to be shared among two servers and allow multi-thread writing to the file, or have a stateless minter (https://github.com/microservices/noid/blob/master/lib/noid/minter.rb, more reference:  https://github.com/psu-stewardship/active_fedora-noid#custom-minters)

**Comment by pbinkley** [comment]
Here's what Notre Dame is doing: it looks like they had the same problem we have. https://groups.google.com/d/msg/hydra-tech/XiHRgzPHyZc/quR67lI7DQAJ . Note Esme's link on how to get Fedora to mint PIDs using an external service as well.

**Comment by pbinkley** [comment]
Options
- two servers, one state file, with locking - we don't have a good solution for this
- route all noid-minting operations to one server
- external noid minter like ND (but can we use current state?)
- let Fedora mint noids

Criteria:
- can we use our current state?
- single point of failure?
- robustness?

**Comment by mbarnett** [comment]
I'm going to update this ticket with information I discover as I read through the source of everything, so apologies in advance for the spam.

RE: "two servers, one state file, with locking" -- Sufia::Noid uses ActiveFedora::Noid::Service which uses [ActiveFedora::Noid::SynchronizedMinter ](https://github.com/psu-stewardship/active_fedora-noid/blob/master/lib/active_fedora/noid/synchronized_minter.rb), which uses blocking and exclusive locks on the minter statefile already, so locking is already baked in in this case.

But it does not sound like we have a solution for sharing the file across servers, so I will investigate moving the state into ND's minter, next.

**Comment by mbarnett** [comment]
Reading through [Notre Dame's noid minter](https://github.com/ndlib/noids) source code:

it's deterministic (therefore replayable), multi-server friendly, and if we were ever to catastrophically lose the server, telling a new instance of it the last noid the old server minted, and the template it was using, is sufficient to restore its state. Failure recovery is pretty straightforward and only requires inspecting the noids in fedora, in this case.

Without modifying it's source code (which I wouldn't want to do on this tight of a timeline) cannot use our current state with it, but there are a couple of options to get around that:

1) If we use the same template as the current minter (".reeddeeddk"), we could tell it to "burn" every noid we've minted so far. However, because it is deterministic it always generates noids in the same sequence, meaning, to burn a given noid it has to *also* burn every other noid it would have generated up to that noid in the sequence. I haven't tested this but if we're unlucky we could burn a very large number of the total noid space, which is probably undesirable.

2) We could simply add a prefix to the template ("a.reeddeeddk") will never generate a noid that conflicts with the original set of minted noids, and gives us full use of the noid space for new mintings.

**Comment by mbarnett** [comment]
It looks like the easiest way to integrate an external minter like the Notre Dame solution would be by via [Configuring Fedora 4 to use an external minter](https://wiki.duraspace.org/display/FEDORA4x/Configuring+an+External+PID+Minter) and then telling Sufia to stop doing the minting in ruby via ```Sufia.config.enable_noids = false```

My concern right now is that all of our Batch logic seems to be built around minting *inside* the app. Various places where the logic would need to change:

https://github.com/ualbertalib/HydraNorth/search?utf8=%E2%9C%93&q=mint

https://github.com/ualbertalib/HydraNorth/search?utf8=%E2%9C%93&q=Batch.find_or_create&type=Code

I will need to put some cycles into what the implications of externalizing the minting to Fedora and how much of our code that will break.

**Comment by henryzhang87** [comment]
with the template ".reeddeeddk", the maximal number of NOID id is MAX_NOIDS=7072810000.

By ActiveFedora:;Noid's implementation, MAX_NOIDS is subdivided into 293 groups, each group has 24139283 ids. The group_id=1,2,3,...,293

The quasi randomness is based on the group_id. Every time when a id is requested, a group id is randomly chosen, inside that group, the next number is in sequence, and thus deterministic.

I agree with you to use prefix. Also, we can let each HydraNorth application server run its own NOID minter for performance, scalability and high availability. The only thing we need to keep in mind is to backup the minter-state file.

**Comment by pbinkley** [comment]
Could we do a very frequent backup of the state files, like we do with
payment data on the ILS, which I think runs every 15 minutes?

**Comment by pbinkley** [comment]
So: at launch, we're using a single app server and a single minter. Post launch we'll implement the two-minter, prefixed solution.
