### ISSUE TITLE
'download full-sized ...' link appears twice on item page

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/HydraNorth#722]
The 'download full-size pdf, image, etc.' link appears twice on the item page, once with the item title:

e.g.: https://hydranorth.library.ualberta.ca/files/w0892c024#.Vh1ZWkZSn9U

![download_full_size](https://cloud.githubusercontent.com/assets/4697932/10465659/3d3b9ffa-71ad-11e5-81e8-b3eae0377539.jpg)

**Comment by weiweishi** [comment]
I think this happens because the thumbnail is not yet in place. The first
link with the title would be the embedded link for the thumbnail image.

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by sfarnel** [comment]
ah, thanks Weiwei.
