### ISSUE TITLE
Collection page doesn't show all the children objects

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#729]
As noted by @johnhuck in #724 Collection page doesn't seem to show all of the children objects. Initially thought it's related to access_control in solr params. But later discovered that even without the access control, the following query only retrieves 6 items, instead of 16.
ActiveFedora::SolrService.instance.conn.get "select", :params => { fl:['id'], fq: "{!join from=hasCollectionMember_ssim to=id}id:44558r821"}

The collection 44558r821 has the following hasCollectionMember_ssim:
 "hasCollectionMember_ssim"=>["44558s04v", "44558s100", "44558s17x", "44558s19g", "44558s25m", "44558s50z", "44558t042", "44558t149", "44558t18d", "44558t31z", "44558t37m", "44558t55j", "44558t73g", "44558v226", "44558v49m", "44558v757"],

And all the objects listed above exist in ActiveFedora.

**Comment by weiweishi** [comment]
Always returns the following 6 children.   
   {
        "id": "44558v757"
      },
      {
        "id": "44558v226"
      },
      {
        "id": "44558s50z"
      },
      {
        "id": "44558s04v"
      },
      {
        "id": "44558s17x"
      },
      {
        "id": "44558s25m"
      }

Some research by @pgwillia indicating that join may not be supported by solr cloud for solr version 4.X:
https://support.lucidworks.com/hc/en-us/articles/201298257-Sharding-w-joins-SolrCloud-question
https://issues.apache.org/jira/browse/SOLR-4905
It seems the issue is fixed by solr 5.1. 

Question now:

Can we get around this by customizing our code:
https://github.com/projecthydra/hydra-collections/blob/master/app/controllers/concerns/hydra/collections_controller_behavior.rb#L153-L162
or 
https://github.com/projecthydra/hydra-collections/blob/master/lib/hydra/collections/search_behaviors.rb

**Comment by weiweishi** [comment]
@mbarnett my code is in include_collection_ids_filter branch. 

I was trying to override:
https://github.com/projecthydra/hydra-collections/blob/master/lib/hydra/collections/search_behaviors.rb 
and 
https://github.com/projecthydra/hydra-collections/blob/master/app/search_builders/hydra/collections/search_builder.rb

Plano is on this branch, and loaded with communities/collections to test.

**Comment by mbarnett** [comment]
Can you double-check that you pushed everything? I'm seeing the https://github.com/ualbertalib/HydraNorth/commits/include_collection_ids_filter branch, but there's nothing on it that isn't already on master

**Comment by weiweishi** [comment]
sorry. @mbarnett committed the change this time and pushed it.

**Comment by mbarnett** [comment]
Thanks! :smiley:

**Comment by mbarnett** [comment]
@weiweishi @pbinkley @pgwillia cc: anyone else who understands this

It seems like our data is really inconsistently denormalized, so I'm not sure we're going to be able to get away from this join without changing our data model? Maybe I'm just misunderstanding something. 

Here's an example:

I'm working with this collection on plano: https://plano.library.ualberta.ca/collections/5425kb035 (it looks empty but that's just because of the branch that's on plano AFAIK)

Using the original join query:

```ruby
ActiveFedora::SolrService.instance.conn.get "select", :params => { fl:['id'], fq: "{!join from=hasCollectionMember_ssim to=id}id:5425kb035"}
```
tells me that there are 2989 members. Whether or not this is accurate, or some are missing, I'm not sure.

Weiwei's initial fix was to change this query to 
```
ActiveFedora::SolrService.instance.conn.get "select", :params => { fl:['id'], q: "collection_tesim:5425kb035"}
```

But this gives no results, because only collections have the collection_tesim property. With GenericFiles the equivalent property is named hasCollection_tesim (which has the name, not the ID) instead (additionally *some* GenericFiles also have the id on hasCollectionId_tesim, but many do not). Changing the query to:

```ruby
ActiveFedora::SolrService.instance.conn.get "select", :params => { fl:['id'], q: 'collection_tesim:5425kb035 OR hasCollectionId_tesim:5425kb035 OR hasCollection_tesim:"Theses and Dissertations Spring 2009 to present"'}
```

gives me 2030 results. 959 missing from the join approach. What's in those missing 959?

```ruby
ActiveFedora::SolrService.instance.conn.get "select", :params => { fl:['id'], fq: "{!join from=hasCollectionMember_ssim to=id}id:5425kb035", q: '-(collection_tesim:5425kb035 OR hasCollectionId_tesim:5425kb035 OR hasCollection_tesim:"Theses and Dissertations Spring 2009 to present")'}
```
This gives the "missing" 959. An example from this set would be https://plano.library.ualberta.ca/files/5x21tf715.

```ruby
f = GenericFile.find('5x21tf715')
f.to_solr.keys

=> ["system_create_dtsi", "system_modified_dtsi", "active_fedora_model_ssi", "has_model_ssim", :id, "object_profile_ssm", "depositor_ssim", "depositor_tesim", "resource_type_tesim", "resource_type_sim", "title_tesim", "title_sim", "creator_tesim", "creator_sim", "description_tesim", "rights_tesim", "date_created_tesim", "date_created_ssi", "date_modified_dtsi", "subject_tesim", "subject_sim", "language_tesim", "language_sim", "isPartOf_ssim", "date_uploaded_ssi", "license_tesim", "trid_tesim", "trid_si", "ser_tesim", "ser_si", "is_version_of_tesim", "unicorn_tesim", "fedora3uuid_tesim", "fedora3handle_tesim", "ingestbatch_tesim", "year_created_tesim", "year_created_sim", "degree_grantor_tesim", "dissertant_tesim", "supervisor_tesim", "committee_member_tesim", "department_tesim", "specialization_tesim", "date_submitted_tesim", "date_accepted_tesim", "graduation_date_tesim", "graduation_date_sim", "thesis_name_tesim", "thesis_level_tesim", "proquest_tesim", "abstract_tesim", "label_tesim", "file_format_tesim", "file_format_sim", "all_text_timv", "file_size_is", "read_access_group_ssim", "edit_access_person_ssim"]
```

There's nothing stored on this file that links it back to the collection, as far as I can see? We would have to run a join against hasCollectionMember_ssim to find it.

**Comment by mbarnett** [comment]
(Or apparently plano's data is just super old and ignore this)

**Comment by pbinkley** [comment]
I think you want  _ssim rather than  _tesim for all those fields, since
there's no need to tokenize when you're trying to get precise matches. I'm
checking now to see if that makes a difference.

Peter Binkley, Ph.D., MLIS
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by pbinkley** [comment]
We really should be using _ssim rather than _tesim fields in https://github.com/ualbertalib/HydraNorth/blob/818c1bbee614816e8f65aaff45cdc32e79c7cc0e/app/controllers/concerns/hydranorth/collections_controller_behavior.rb#L21 . Fields with t are tokenized and stemmed, so there's risk of imprecise matches - e.g. the current index includes a hasCollectionId_tesim value ```44558t34``` (one character too short) - that collection doesn't exist, but ```44558t34s``` does. The query still works (since querying against a stemmed field also stems the query), but some day we may generate noids that get stemmed in such a way that two collections have the same value.

**Comment by johnhuck** [comment]
in release v.1.0.6 it looks like all collections and items within communities are missing from the display pages accessible from https://hydranorth.library.ualberta.ca/communities

**Comment by anayram** [comment]
I had the same experience for any communities accessible either from the page @johnhuck mentions, or from search and links to collections from item pages.

**Comment by pgwillia** [comment]
Might be related to this change https://github.com/ualbertalib/HydraNorth/commit/efa623d9745e3f9b6b050ee0dd8315b17dc69f86 
```
-      if current_user && current_user.admin?
-        self.search_params_logic -= [:add_access_controls_to_solr_params]
-      end
-
+      self.search_params_logic -= [:add_access_controls_to_solr_params]
```
[https://github.com/ualbertalib/HydraNorth/blame/master/app/controllers/concerns/hydranorth/collections_controller_behavior.rb#L7]

Also would explain the latest failing tests https://github.com/ualbertalib/HydraNorth/issues/686

**Comment by pbinkley** [comment]
Gathering full example.

Here's FGSR community: https://hydranorth.library.ualberta.ca/collections/44558r66n  . Shows no collections or items.

Here's the pre-2009 thesis collection: https://hydranorth.library.ualberta.ca/files/w0892c619#.ViAQSZcy3mE . Belongs to FGSR community (with correct link). No items appear.

Here's a previous-migrated thesis: https://hydranorth.library.ualberta.ca/files/wm117p249#.ViAPjZcy3mE - belongs to FGSR community (with correct link) but no collection.

Here's a newly-migrated thesis: https://hydranorth.library.ualberta.ca/files/w0892c619#.ViAQSZcy3mE - belongs to FGSR community (with correct link) and pre-2009 collection (with correct link)

**Comment by weiweishi** [comment]
That was a WIP and I don't think it's been fully tested as all. 

-      if current_user && current_user.admin?
-        self.search_params_logic -= [:add_access_controls_to_solr_params]
-      end
-
+      self.search_params_logic -= [:add_access_controls_to_solr_params]
[https://github.com/ualbertalib/HydraNorth/blame/master/app/controllers/concerns/hydranorth/collections_controller_behavior.rb#L7]

**Comment by pbinkley** [comment]
Another example:

An image: https://hydranorth.library.ualberta.ca/files/ff365524z#.ViASY5cy3mE - belongs to Dept. of Anthropology community and Bryan/Gruhn Archaeology Collection. 

Collection: https://hydranorth.library.ualberta.ca/collections/44558t46k (note: slow to load, as if it were processing its items, but it doesn't display them).

Community: https://hydranorth.library.ualberta.ca/collections/44558r023

**Comment by mbarnett** [comment]
I'm not clear on why this merge was made: https://github.com/ualbertalib/HydraNorth/pull/747 but that branch wasn't working at all and shouldn't have been merged into master yet.

I'd revert it from here but I don't trust myself to not delete the repo in a feverish fugue state. Sorry to have been away for this confusion,

**Comment by pbinkley** [comment]
We're reaching the same conclusion. It was my rush to get stuff into the release. We'll get it sorted out.
