### ISSUE TITLE
Rights statement cut off

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/HydraNorth#780]
For some items the rights string is cut off.

E.g., https://hydranorth.library.ualberta.ca/files/wh246s128#.ViFwhkZSn9U

![righths](https://cloud.githubusercontent.com/assets/4697932/10554112/c2e8faae-741d-11e5-9660-981cf0fb50c8.jpg)

e.g., https://hydranorth.library.ualberta.ca/files/ff365650s#.ViFx_UZSn9U

**Comment by pbinkley** [comment]
The rights statement seems to be drawn from the the LABEL attribute of the datastream in the foxml, instead of from the content of the datastream:

```<foxml:datastreamVersion ID="LICENSE.5" LABEL="Use of this product is restricted to current faculty,..." CREATED="2014-04-24T18:09:34.399Z" MIMETYPE="text/plain">```

The truncated form from the label was displayed in old ERA and you had to click the "download license" link to see the full text. This item fell through to the ```else``` at https://github.com/ualbertalib/HydraNorth/blob/master/lib/tasks/migration.rake#L421 . The downloading of the license file was only triggered by the presence of a filename in the LABEL attribute, handled by https://github.com/ualbertalib/HydraNorth/blob/master/lib/tasks/migration.rake#L370 .

We should import the full text for all items with this rights statement, as a data cleanup task (once we're past our current stability problems).

Full text:

> Use of this product is restricted to current faculty, staff, and students of the University. It is the responsibility of each user to ensure that he or she uses this product for individual, non-commercial educational or research purposes only, and does not systematically download or retain substantial portions of information.  Users may not reproduce or redistribute unprocessed/raw data portions of the data to any third party, or otherwise engage in the systematic retransmission or commercialization of the data.

**Comment by pbinkley** [comment]
Resolve as part of audit.

**Comment by sfarnel** [comment]
Captured in #977
