### ISSUE TITLE
ERA_Collections: Allow user to add item to any collections

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#79]
As a user and as admin I want to be able to associate items with multiple official collections, so that I don’t have to deposit the same item twice for it to show up in two different collections (use case: a co-authored paper between a chemical engineer and a surgeon should be deposited once but accessible through both a ‘department of chemical engineering papers’ and a ‘department of surgery papers’ collection). Sufia allows this, but only to collections that the user owns. So we need to add ability to add to other collections, except locked collections (e.g. Theses)

**Comment by pbinkley** [comment]
Current Sufia functionality: a depositor can add items to multiple collections, but only their own items to collections they own. Tricia working on allowing admin to add any item to any collection. #65 That will only leav qustions around workflow, if any.

**Comment by pgwillia** [comment]
I propose that we solve this by allowing appropriate [Sufia::Permissions::Writable](https://github.com/projecthydra/sufia/blob/master/sufia-models/app/models/concerns/sufia/collection_behavior.rb#L14-L16) to be set by admin. This would mean adding the permissions form to editing collections which might look something like:
![image](https://cloud.githubusercontent.com/assets/1220762/7192911/9bf22188-e457-11e4-97cb-56330a4693e9.png)
The content in the red rectangle would not appear to non-admin users.

Test cases:

description|edit group permissions| edit users permissions
--------------|-----------------------------|----------------------------
user collection | none | user
admin collection | none | admin user
open admin collection | registered | admin user
locked admin collection | admin | admin user

* for all cases read_group permissions are open so that everyone can search all collections
* when an admin collection creates a collection it is considered a user collection which happens to be owned by an admin user until they change the permissions.

And then the collection options a user is presented with when they select "Add to Collection" include
collections with edit permissions granted to their user and any group that their user has membership in:

user|add to collection|not in list
------|--------------------|------------
user|user collection, open admin collection| admin collection, locked admin collection
admin user| admin collection, open admin collection, locked admin collection| user collection
other admin user| open admin collection, locked admin collection | user collection, admin collection

"My Collections" on the dashboard would continue to consist of the collections where the user is the 'depositor.'

**Comment by pgwillia** [comment]
Note that this approach would leave unlocked official collections open to edit/destroy by registered users. Separate permissions/access controls for collection and membership would be breaking new ground and would not be a small task.

**Comment by sfbetz** [comment]
captured in #876 , #909 , #76 , #735
