### ISSUE TITLE
Google Scholar Indexing (1): Modify Download URLs with .pdf

### ISSUE THREAD

**Issue by johnhuck** [ualbertalib/HydraNorth#848]
Issue 1 of Epic #435.

With reference to UAL's [Google Scholar Strategy document] (https://docs.google.com/document/d/1t8LMGsYEQtkvWOSGHLXJDGJ-8fLVPgumrBqwWHQjkMY/edit#bookmark=id.jd4nolw32z5s).

Modify download URLs so they end in .pdf

**Comment by weiweishi** [comment]
need to test the download for files that are not characterized properly (docx, pptx etc).

**Comment by pbinkley** [comment]
Easiest implemention: use the original filename, as stored in the file label attribute, in the URL, instead of DS1. This is the filename that is passed in the header when the file is downloaded, so it is consistent.

**Comment by pbinkley** [comment]
It may be easy to close #849 at the same time (putting the pdf url in the DC.identifier tag)

**Comment by pbinkley** [comment]
And we should investigate whether the new url will affect the registering of downloads for analytics purposes, and whether we can fix it if it does.

**Comment by pbinkley** [comment]
Looking again at #849, I realize it has to be done along with this, and it requires a change in the urls structure:

Instead of

https://era.library.ualberta.ca/downloads/j098zd881/120715_parliamentnow.pdf

We need

https://era.library.ualberta.ca/files/j098zd881/120715_parliamentnow.pdf

That way the pdf's url is "in the same directory" as the object.
