### ISSUE TITLE
Some files hanging up on upload

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#862]
We are unable to upload these files - they sit in the queue processing, but don't finish and the metadata doesn't stick. We've tried multiple times to upload - not sure what the problem is? 

https://era.library.ualberta.ca/files/b2n49t168w#.VlN6ot-rSEJ
https://era.library.ualberta.ca/files/bp2676v527#.VlN7Xt-rSEI

**Comment by pbinkley** [comment]
I'm looking at the second one. Processing is tracked at the batch level,
and the batch for this is thought to be processing:

=> #<Batch id: "b6682x394v", creator: [], title: [], status: ["processing"]>

But there's nothing in the queue on leyton. (The "b" prefix shows this is a
leyton item). Processing must have failed, though it got to the point of
generating a thumbnail and deriving the file_author etc. i.e. it could
parse the pdf.

In the logs for Nov. 18 we find:

E, [2015-11-18T14:03:05.073816 #2199] ERROR -- : Error extracting content
from bp2676v527: #<RuntimeError: URL '
http://tottenham.library.ualberta.ca:8080/solr/hydranorth/update/extract?extractOnly=true&wt=json&extractFormat=text'
returned code 500>

I.e. Solr threw an error when it tried to extract the text from the pdf.
That must have left the process hanging. I'll put in a bug report for this.

I have set the batch's status to "Complete" in the rails console:

irb(main):002:0* x = Batch.find('b6682x394v')
=> #<Batch id: "b6682x394v", creator: [], title: [], status: ["processing"]>
irb(main):003:0> x.update(status: ["Complete"])
=> true
irb(main):004:0> x
=> #<Batch id: "b6682x394v", creator: [], title: [], status: ["Complete"]>



(copying the update command from
https://github.com/projecthydra/sufia/blob/0402cd00e52e621c146b007ccbb5aa02c60a15fd/sufia-models/app/jobs/batch_update_job.rb#L29
)

It's now editable. I filled in the required fields (making guesses at the
ones I didn't know, like subject - the license is stated on the first page
of the pdf). Please have a look and see what else needs fixing. It is still
private. I've assigned it to the ERA Processing community, since that's a
required field.

I'll change the flag on the other one, but I won't do any editing.

Peter

Peter Binkley, Ph.D., MLIS
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by pbinkley** [comment]
I've fixed the other item so it is available to edit, and I've put in a bug
issue: https://github.com/ualbertalib/HydraNorth/issues/863 .

**Comment by sfbetz** [comment]
Is this also happening here?  https://era.library.ualberta.ca/files/tb09j833q#.VlNQs7OjNcY

**Comment by sfbetz** [comment]
Moving into postproduction and changing priority to high - hoping we can get this into next sprint?

**Comment by pbinkley** [comment]
Should have been fixed by #883 - check after next release

**Comment by sfbetz** [comment]
resolved
