### ISSUE TITLE
audit the migrated items

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#886]
- [x] audit all the migrated items
- [ ] migrate the items that was failed to migrate during previous attempts.

**Comment by weiweishi** [comment]
Issues identified (WIP):
- [ ] date_uploaded for thesis objects (Migration used dateaccepted/datesubmitted for thesis, audit checked the CREATED flag for the last datastream version. )

**Comment by weiweishi** [comment]
Some notes from @sfarnel 
dcterms:dateaccepted and dcterms;datesubmitted were set up initially for e-theses to reflect the theses review and approval workflow. that is, datesubmitted was when the student submits the thesis for review and approval, and dateaccepted is the date that FGSR approves the thesis and the student can then convocate. and so in the ERA context these two dates are really only semantically relevant to e-theses

so this is why you will find many, many items that don't have these dates.

however, at some point in ERA's development (Piyapong might be able to shed light on this), non-thesis items uploaded via the interface started having the datesubmitted and dateaccepted dates populated automatically at the time of ingest into ERA.

because of this, many non-theses items had this in their descriptive metadata and this was retained and transformed for migration.

for those items that don't have dateaccepted or datesubmitted in their DCQ datastream (e.g., wd375x836, migrated from uuid:d675948a-23b5-49d0-9016-01a9a80cfc35), we should look elsewhere.

where we look may be a slightly bigger conversation, though. if you look at the example above (wd375x836) the date/time for the audit record type=ingest is 2012-06-05T16:02:10.201Z. i would suggest that ingest is a reasonable date to use.

but you'll also see by the audit entries that a DS version was purged and so the date/time on the DS1 datastream reflects this later activity - 2014-04-25T03:26:21.914Z

so perhaps this is a better source as it would reflect the most recent activity on the object file.

i think i would still argue for initial ingest but others (Sonya, Peter, etc.) may feel differently.
********************
Checked with @sfbetz and @pbinkley, and all in agreement that initial ingest date should be used for the date_uploaded. We should rely on other information (date_modified,  visibility setting etc) to allow the out-of-embargo objects be added to the OAI set). 
I will proceed with this assumption, and write a task to update the date_uploaded field accordingly.

**Comment by sfarnel** [comment]
Great; thanks @weiweishi @sfbetz @pbinkley

**Comment by zschoenb** [comment]
Some notes:

**date_uploaded:**
35844 discrepancies
11575 original values different from transformed values
    24-Apr-2014 (10804 occurrences)
2802 where only the time (not the date) is mismatched (no significant difference)
21467 with original date value (no transformed date value):
    6-Jan-2010(2170)
    2-May-2014(231)
    16-Sep-2011(105)
    15-Sep-2011(243)
January 2014: date uploaded begins being recorded with these prior exceptions:
uuid:0b550b39-b8c2-4a05-874f-80e7bd2515ea, 2010-01-05T00:00:00Z, 2010-01-05T00:00:00Z
uuid:aaa65dd8-5960-44cd-88f9-f9d4f91b75db, 2013-09-10T00:00:00Z, 2013-09-10T00:00:00Z

**depositor:**
These are the deposit ids to which old ids are being transformed:
    cihrgrants@ualberta.ca (102)
    csweb@ualberta.ca (2)
    eraadmi@ualberta.ca (1)
    gapsshrc@ualberta.ca (47)
    haiuofa@ualberta.ca (8)

**description:**
removal or addition of special characters, particularly escape slashes

**has_collection:**
Normal changes of collection names
Except:
Some CIHR items belong to no collection:
    5t34sk55r,3x816p003,vq27zp152,x346d500g,dr26xx537,54xk18z,fb4948624,p5547s818
Some CIHR items not previously belonging to collections:
    0z708w746,r207tq17h,vq27zp152
Now belong to: 
    Grant Assist Program (Health Sciences)
    University Delegate (CIHR) Information) 
CIHR items are created by the "CIHR" author:
    https://era.library.ualberta.ca/catalog?f[creator_sim][]=CIHR
The "CIHR" author has created other items that were not picked up by the audit. These items belong to the following collections. 
    University Delegate (CIHR) Information (12): https://era.library.ualberta.ca/catalog?f%5Bcreator_sim%5D%5B%5D=CIHR&f%5BhasCollection_ssim%5D%5B%5D=University+Delegate+%28CIHR%29+Information
    Workshops – non-OOGP non-training competitions (2)
    Foundation Competition Resources (1)
    Foundation Competition Workshops (1)
    Workshops – Trainee Awards (1)

**is_version_of:**
    blank -> blank (whats happening?)
    spec. chars -> blank
    repeating values -> blank

**subject:**
    appears to be understandable changes (de-dupes etc)
    some special characters introduced: 
        & -> &amp

**Comment by pbinkley** [comment]
Status: @anayram has prepared a new list of objects with post-migration changes in thesisdeposit and unmigrated items for migration/remigration
