### ISSUE TITLE
Error in community after editing files

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#913]
I created an error viewing a community today after helping a faculty member edit files.

We edited files in this collection:
https://era.library.ualberta.ca/collections/44558r03c
from this community:
https://era.library.ualberta.ca/collections/44558s984

We edited only the subject keywords of these files:
https://era.library.ualberta.ca/files/05741s76w
https://era.library.ualberta.ca/files/2227mr07z

The collection field was empty for both items (bug #902 ). We saved both items successfully, and could navigate to both of them, but when we tried to click on the community https://era.library.ualberta.ca/collections/44558s984 we received the "something's went wrong" error. 

@pbinkley fixed the items and all is working well now for this community.

Same issue is occurring in Dept of Economics community as well: https://era.library.ualberta.ca/collections/44558r39r

**Comment by sfbetz** [comment]
And here:
https://era.library.ualberta.ca/collections/44558r821

Once we fix the bug, is there a process we can run to find any orphans and restore their collection ids?

**Comment by pbinkley** [comment]
The underlying problem was that the items had their hasCollectionId set to an empty array when they were saved: ```hasCollection: ["Successful Grants Library"], belongsToCommunity: ["44558r03c"], hasCollectionId: [], ```. Resetting it to the an array containing the id of the original collection fixed the item, and fixing both items fixed the community view, so presumably the community view problem was an effect of the inconsistent data in these items.
So the basic problem is to make sure the hasCollectionId does not lose its value when an item is edited. 
Could #909 and #910 be related?

**Comment by pbinkley** [comment]
​We should be able to detect them by looking for items with collection
names but no collection ids. ​

Peter Binkley, Ph.D., MLIS
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243
